/* ============================================================
   分子语堂 · 六级词库 + 翻译表达库
   每日仪表盘 / 六级备考中心 / 资料包下载共用
   ============================================================ */

/* ---------- 六级高频词 645 个（页面动态计数） ---------- */
window.MST_WORDS6 = [
  { w: "abolish", p: "/əˈbɒlɪʃ/", m: "v. 废除，废止（法律、制度）", e: "The outdated regulation was <b>abolished</b> last year." },
  { w: "accommodate", p: "/əˈkɒmədeɪt/", m: "v. 容纳；为…提供住宿；使适应", e: "The hall can <b>accommodate</b> 500 people." },
  { w: "accumulate", p: "/əˈkjuːmjəleɪt/", m: "v. 积累，积聚", e: "Dust <b>accumulated</b> on the valves over time." },
  { w: "acute", p: "/əˈkjuːt/", m: "adj. 严重的；敏锐的；急性的", e: "The region faces an <b>acute</b> shortage of water." },
  { w: "adhere", p: "/ədˈhɪə/", m: "v. 粘附；坚持（adhere to）", e: "All staff must <b>adhere to</b> safety procedures." },
  { w: "advocate", p: "/ˈædvəkeɪt/", m: "v. 提倡 n. 拥护者", e: "Experts <b>advocate</b> stricter emission standards." },
  { w: "aggravate", p: "/ˈæɡrəveɪt/", m: "v. 加剧，使恶化", e: "The leak <b>aggravated</b> the situation." },
  { w: "alleviate", p: "/əˈliːvieɪt/", m: "v. 减轻，缓解", e: "The new pump <b>alleviated</b> pressure on the system." },
  { w: "ambiguous", p: "/æmˈbɪɡjuəs/", m: "adj. 模棱两可的，含糊不清的", e: "His statement was deliberately <b>ambiguous</b>." },
  { w: "analogy", p: "/əˈnælədʒi/", m: "n. 类比（draw an analogy）", e: "The teacher drew an <b>analogy</b> between heat and electricity." },
  { w: "anonymous", p: "/əˈnɒnɪməs/", m: "adj. 匿名的", e: "The donation came from an <b>anonymous</b> donor." },
  { w: "anticipate", p: "/ænˈtɪsɪpeɪt/", m: "v. 预期，预料", e: "Analysts <b>anticipate</b> a rise in demand." },
  { w: "apparatus", p: "/ˌæpəˈreɪtəs/", m: "n. 器械，装置，设备", e: "The laboratory apparatus was thoroughly cleaned." },
  { w: "arbitrary", p: "/ˈɑːbɪtrəri/", m: "adj. 任意的；武断的", e: "The decision seemed completely <b>arbitrary</b>." },
  { w: "articulate", p: "/ɑːˈtɪkjuleɪt/", m: "v. 清晰表达 adj. 口齿伶俐的", e: "She <b>articulated</b> the plan clearly to the team." },
  { w: "ascribe", p: "/əˈskraɪb/", m: "v. 归因于（ascribe A to B）", e: "They <b>ascribed</b> the failure to corrosion." },
  { w: "assess", p: "/əˈses/", m: "v. 评估，评定", e: "We need to <b>assess</b> the risks before start-up." },
  { w: "attain", p: "/əˈteɪn/", m: "v. 达到，获得", e: "The process <b>attains</b> a yield of 95 percent." },
  { w: "authentic", p: "/ɔːˈθentɪk/", m: "adj. 真实的；可靠的", e: "The report is based on <b>authentic</b> data." },
  { w: "avert", p: "/əˈvɜːt/", m: "v. 避免，防止；转移", e: "Quick action <b>averted</b> a major crisis." },
  { w: "bleak", p: "/bliːk/", m: "adj. 荒凉的；暗淡的", e: "The economic outlook remains <b>bleak</b>." },
  { w: "blunder", p: "/ˈblʌndə/", m: "n. 大错 v. 犯大错", e: "Skipping the safety check was a fatal <b>blunder</b>." },
  { w: "boost", p: "/buːst/", m: "v./n. 提高，推动", e: "The upgrade <b>boosted</b> efficiency by 20 percent." },
  { w: "breach", p: "/briːtʃ/", m: "n. 违反；缺口 v. 违反", e: "The company was fined for a <b>breach</b> of contract." },
  { w: "brutal", p: "/ˈbruːtl/", m: "adj. 残忍的；严酷的", e: "The equipment endured <b>brutal</b> conditions." },
  { w: "capture", p: "/ˈkæptʃə/", m: "v. 捕获；捕捉；吸引", e: "The unit <b>captures</b> CO₂ from flue gas." },
  { w: "cherish", p: "/ˈtʃerɪʃ/", m: "v. 珍视，珍爱", e: "She <b>cherishes</b> the memory of her first experiment." },
  { w: "coincide", p: "/ˌkəʊɪnˈsaɪd/", m: "v. 同时发生；相符（coincide with）", e: "The shutdown <b>coincided with</b> the holiday." },
  { w: "collaborate", p: "/kəˈlæbəreɪt/", m: "v. 合作，协作", e: "The two labs <b>collaborated</b> on the project." },
  { w: "commence", p: "/kəˈmens/", m: "v. 开始，着手", e: "Operations will <b>commence</b> next Monday." },
  { w: "compact", p: "/ˈkɒmpækt/", m: "adj. 紧凑的；小型的", e: "They installed a <b>compact</b> heat exchanger." },
  { w: "compatible", p: "/kəmˈpætəbl/", m: "adj. 兼容的；合得来的（compatible with）", e: "The sensor is <b>compatible with</b> the old system." },
  { w: "compensate", p: "/ˈkɒmpenseɪt/", m: "v. 补偿，弥补（compensate for）", e: "The bonus <b>compensated for</b> the overtime." },
  { w: "compile", p: "/kəmˈpaɪl/", m: "v. 汇编，编制", e: "They <b>compiled</b> a database of accidents." },
  { w: "comply", p: "/kəmˈplaɪ/", m: "v. 遵守（comply with）", e: "All plants must <b>comply with</b> the safety code." },
  { w: "comprehensive", p: "/ˌkɒmprɪˈhensɪv/", m: "adj. 全面的，综合的", e: "The report gives a <b>comprehensive</b> review." },
  { w: "compulsory", p: "/kəmˈpʌlsəri/", m: "adj. 强制的，必修的", e: "Safety training is <b>compulsory</b> for newcomers." },
  { w: "conceive", p: "/kənˈsiːv/", m: "v. 构想，设想；怀孕", e: "The team <b>conceived</b> a new process route." },
  { w: "confidential", p: "/ˌkɒnfɪˈdenʃl/", m: "adj. 机密的，保密的", e: "The formula remains strictly <b>confidential</b>." },
  { w: "conform", p: "/kənˈfɔːm/", m: "v. 符合，遵照（conform to）", e: "The product <b>conforms to</b> the national standard." },
  { w: "consecutive", p: "/kənˈsekjətɪv/", m: "adj. 连续的", e: "The unit ran for five <b>consecutive</b> days." },
  { w: "consolidate", p: "/kənˈsɒlɪdeɪt/", m: "v. 巩固，加强；合并", e: "The merger <b>consolidated</b> the two plants." },
  { w: "contaminate", p: "/kənˈtæmɪneɪt/", m: "v. 污染，弄脏", e: "Careless handling <b>contaminated</b> the sample." },
  { w: "contemplate", p: "/ˈkɒntəmpleɪt/", m: "v. 沉思；考虑，打算", e: "She <b>contemplated</b> the results for a long while." },
  { w: "contradict", p: "/ˌkɒntrəˈdɪkt/", m: "v. 反驳；与…矛盾", e: "The new data <b>contradicts</b> the earlier theory." },
  { w: "converge", p: "/kənˈvɜːdʒ/", m: "v. 汇聚，聚合", e: "The two research paths <b>converged</b> on one answer." },
  { w: "crucial", p: "/ˈkruːʃl/", m: "adj. 至关重要的", e: "Temperature control is <b>crucial</b> to the process." },
  { w: "cultivate", p: "/ˈkʌltɪveɪt/", m: "v. 培养；耕作", e: "Reading <b>cultivates</b> critical thinking." },
  { w: "curb", p: "/kɜːb/", m: "v./n. 控制，抑制", e: "New rules aim to <b>curb</b> emissions." },
  { w: "deceive", p: "/dɪˈsiːv/", m: "v. 欺骗，蒙蔽", e: "Do not <b>deceive</b> yourself with wishful thinking." },
  { w: "dedicate", p: "/ˈdedɪkeɪt/", m: "v. 奉献，致力于（dedicate to）", e: "He is <b>dedicated to</b> green chemistry." },
  { w: "deduce", p: "/dɪˈdjuːs/", m: "v. 推断，演绎", e: "We can <b>deduce</b> the mechanism from the data." },
  { w: "degrade", p: "/dɪˈɡreɪd/", m: "v. 降低；降解，退化", e: "Plastic <b>degrades</b> very slowly in nature." },
  { w: "deliberate", p: "/dɪˈlɪbərət/", m: "adj. 故意的；从容的 v. 深思", e: "It was a <b>deliberate</b> attempt to cut corners." },
  { w: "denote", p: "/dɪˈnəʊt/", m: "v. 表示，意味着", e: "The symbol K <b>denotes</b> the mass transfer coefficient." },
  { w: "deprive", p: "/dɪˈpraɪv/", m: "v. 剥夺（deprive of）", e: "The drought <b>deprived</b> the region of water." },
  { w: "designate", p: "/ˈdezɪɡneɪt/", m: "v. 指定，命名", e: "The area was <b>designated</b> as a safety zone." },
  { w: "deteriorate", p: "/dɪˈtɪəriəreɪt/", m: "v. 恶化，变坏", e: "The catalyst <b>deteriorated</b> after two years." },
  { w: "deviate", p: "/ˈdiːvieɪt/", m: "v. 偏离（deviate from）", e: "The process <b>deviated from</b> the set parameters." },
  { w: "dilemma", p: "/dɪˈlemə/", m: "n. 困境，进退两难", e: "She faced the <b>dilemma</b> of cost versus safety." },
  { w: "diminish", p: "/dɪˈmɪnɪʃ/", m: "v. 减少，降低", e: "The supply of raw coal gradually <b>diminished</b>." },
  { w: "discern", p: "/dɪˈsɜːn/", m: "v. 辨别，识别", e: "We can <b>discern</b> a clear pattern in the data." },
  { w: "disclose", p: "/dɪsˈkləʊz/", m: "v. 揭露，披露", e: "The report <b>disclosed</b> several safety violations." },
  { w: "discrepancy", p: "/dɪˈskrepənsi/", m: "n. 差异，不一致", e: "There is a <b>discrepancy</b> between theory and measurement." },
  { w: "disperse", p: "/dɪˈspɜːs/", m: "v. 分散，消散", e: "The wind quickly <b>dispersed</b> the gas cloud." },
  { w: "distort", p: "/dɪˈstɔːt/", m: "v. 扭曲，使失真", e: "Bad sampling can <b>distort</b> the results." },
  { w: "divert", p: "/daɪˈvɜːt/", m: "v. 转移，改道", e: "They <b>diverted</b> the flow to the backup line." },
  { w: "drastic", p: "/ˈdræstɪk/", m: "adj. 激烈的，严厉的", e: "<b>Drastic</b> measures are needed to cut losses." },
  { w: "dwell", p: "/dwel/", m: "v. 居住；详述（dwell on）", e: "Do not <b>dwell on</b> past mistakes." },
  { w: "elaborate", p: "/ɪˈlæbəreɪt/", m: "v. 详细说明 adj. 精心制作的", e: "Could you <b>elaborate on</b> the safety concern?" },
  { w: "elevate", p: "/ˈelɪveɪt/", m: "v. 提升，抬高", e: "They <b>elevated</b> the reactor temperature by 5 degrees." },
  { w: "embark", p: "/ɪmˈbɑːk/", m: "v. 着手，从事（embark on）", e: "She <b>embarked on</b> a career in process design." },
  { w: "endeavor", p: "/ɪnˈdevə/", m: "n./v. 努力，尝试", e: "Scientific <b>endeavors</b> require patience." },
  { w: "enhance", p: "/ɪnˈhɑːns/", m: "v. 增强，提高", e: "Fins <b>enhance</b> heat transfer on the tube side." },
  { w: "enroll", p: "/ɪnˈrəʊl/", m: "v. 注册，登记（enroll in）", e: "He <b>enrolled in</b> an evening English course." },
  { w: "epidemic", p: "/ˌepɪˈdemɪk/", m: "n. 流行病 adj. 流行的", e: "The city survived a flu <b>epidemic</b>." },
  { w: "erode", p: "/ɪˈrəʊd/", m: "v. 侵蚀，腐蚀", e: "Acid <b>eroded</b> the pipeline wall." },
  { w: "evoke", p: "/ɪˈvəʊk/", m: "v. 唤起，引起", e: "The photo <b>evoked</b> memories of campus life." },
  { w: "exacerbate", p: "/ɪɡˈzæsəbeɪt/", m: "v. 使加剧，使恶化", e: "The strike <b>exacerbated</b> the supply shortage." },
  { w: "facilitate", p: "/fəˈsɪlɪteɪt/", m: "v. 促进，使便利", e: "Stirring <b>facilitates</b> the reaction." },
  { w: "feasible", p: "/ˈfiːzəbl/", m: "adj. 可行的", e: "The plan is technically <b>feasible</b> but costly." },
  { w: "flaw", p: "/flɔː/", m: "n. 缺陷，瑕疵", e: "A design <b>flaw</b> caused the failure." },
  { w: "fluctuate", p: "/ˈflʌktʃueɪt/", m: "v. 波动，起伏", e: "Prices <b>fluctuate</b> according to demand." },
  { w: "formulate", p: "/ˈfɔːmjuleɪt/", m: "v. 制定；系统地阐述", e: "The team <b>formulated</b> a response strategy." },
  { w: "foster", p: "/ˈfɒstə/", m: "v. 培养，促进", e: "Competition can <b>foster</b> innovation." },
  { w: "fragile", p: "/ˈfrædʒaɪl/", m: "adj. 易碎的，脆弱的", e: "Handle the <b>fragile</b> glass column with care." },
  { w: "gauge", p: "/ɡeɪdʒ/", m: "n. 计量表 v. 测量，判断", e: "Check the pressure <b>gauge</b> every hour." },
  { w: "hamper", p: "/ˈhæmpə/", m: "v. 妨碍，阻碍", e: "Poor visibility <b>hampered</b> the inspection." },
  { w: "harness", p: "/ˈhɑːnɪs/", m: "v. 利用；控制 n. 马具", e: "We <b>harness</b> solar energy for heating." },
  { w: "hazard", p: "/ˈhæzəd/", m: "n. 危险，危害", e: "Static electricity is a hidden <b>hazard</b>." },
  { w: "hinder", p: "/ˈhɪndə/", m: "v. 阻碍，妨碍", e: "Low temperature <b>hinders</b> the reaction." },
  { w: "illuminate", p: "/ɪˈluːmɪneɪt/", m: "v. 照亮；阐明", e: "The study <b>illuminates</b> the reaction mechanism." },
  { w: "immerse", p: "/ɪˈmɜːs/", m: "v. 浸泡；使沉浸（immerse in）", e: "<b>Immerse</b> yourself in English every day." },
  { w: "imperative", p: "/ɪmˈperətɪv/", m: "adj. 至关重要的 n. 必要之事", e: "Immediate action is <b>imperative</b>." },
  { w: "impetus", p: "/ˈɪmpɪtəs/", m: "n. 推动力，刺激", e: "The policy gave an <b>impetus</b> to green energy." },
  { w: "impose", p: "/ɪmˈpəʊz/", m: "v. 强加；征收（impose on）", e: "The court <b>imposed</b> a heavy fine on the plant." },
  { w: "incentive", p: "/ɪnˈsentɪv/", m: "n. 激励，动机", e: "Tax breaks are an economic <b>incentive</b>." },
  { w: "inclination", p: "/ˌɪnklɪˈneɪʃn/", m: "n. 倾向，意愿", e: "He showed no <b>inclination</b> to apologize." },
  { w: "indulge", p: "/ɪnˈdʌldʒ/", m: "v. 放纵，沉溺（indulge in）", e: "Do not <b>indulge in</b> wishful thinking." },
  { w: "inherent", p: "/ɪnˈhɪərənt/", m: "adj. 固有的，内在的（inherent in）", e: "Risk is <b>inherent in</b> any chemical process." },
  { w: "initiative", p: "/ɪˈnɪʃətɪv/", m: "n. 主动性；倡议（take the initiative）", e: "She took the <b>initiative</b> to report the leak." },
  { w: "integral", p: "/ˈɪntɪɡrəl/", m: "adj. 不可或缺的（integral part）", e: "Safety is an <b>integral</b> part of the design." },
  { w: "intricate", p: "/ˈɪntrɪkət/", m: "adj. 错综复杂的，精细的", e: "The plant is an <b>intricate</b> network of pipes." },
  { w: "intrinsic", p: "/ɪnˈtrɪnsɪk/", m: "adj. 内在的，本质的", e: "Curiosity is the <b>intrinsic</b> drive of learning." },
  { w: "intuition", p: "/ˌɪntjuˈɪʃn/", m: "n. 直觉", e: "Trust your <b>intuition</b> when data is missing." },
  { w: "jeopardize", p: "/ˈdʒepədaɪz/", m: "v. 危及，损害", e: "One wrong step could <b>jeopardize</b> the whole batch." },
  { w: "legitimate", p: "/lɪˈdʒɪtɪmət/", m: "adj. 合法的；正当的", e: "Price is a <b>legitimate</b> concern for customers." },
  { w: "magnify", p: "/ˈmæɡnɪfaɪ/", m: "v. 放大，扩大", e: "The microscope <b>magnifies</b> the crystal 100 times." },
  { w: "mediate", p: "/ˈmiːdieɪt/", m: "v. 调解，斡旋", e: "The manager <b>mediated</b> the dispute between shifts." },
  { w: "mingle", p: "/ˈmɪŋɡl/", m: "v. 混合，交往（mingle with）", e: "Fresh air <b>mingled with</b> the feed gas." },
  { w: "negligible", p: "/ˈneɡlɪdʒəbl/", m: "adj. 可忽略不计的", e: "The measurement error is <b>negligible</b>." },
  { w: "notorious", p: "/nəʊˈtɔːriəs/", m: "adj. 声名狼藉的（notorious for）", e: "The intersection is <b>notorious</b> for accidents." },
  { w: "nurture", p: "/ˈnɜːtʃə/", m: "v. 培养，养育", e: "Good habits <b>nurture</b> long-term success." },
  { w: "obscure", p: "/əbˈskjʊə/", m: "adj. 晦涩的 v. 使模糊", e: "The jargon <b>obscures</b> the main point." },
  { w: "offset", p: "/ˈɒfset/", m: "v. 抵消，补偿", e: "Higher output <b>offsets</b> the extra cost." },
  { w: "oppress", p: "/əˈpres/", m: "v. 压迫，压抑", e: "Workers were <b>oppressed</b> by the summer heat." },
  { w: "permeate", p: "/ˈpɜːmieɪt/", m: "v. 渗透，弥漫", e: "The smell <b>permeated</b> the whole laboratory." },
  { w: "perpetuate", p: "/pəˈpetʃueɪt/", m: "v. 使长久，使持续", e: "The story <b>perpetuates</b> an old myth." },
  { w: "prevail", p: "/prɪˈveɪl/", m: "v. 盛行；获胜（prevail over）", e: "Common sense should <b>prevail</b> over convenience." },
  { w: "profound", p: "/prəˈfaʊnd/", m: "adj. 深刻的，深远的", e: "The discovery had a <b>profound</b> impact." },
  { w: "prolong", p: "/prəˈlɒŋ/", m: "v. 延长，拖延", e: "Regeneration <b>prolongs</b> the catalyst life." },
  { w: "refute", p: "/rɪˈfjuːt/", m: "v. 驳斥，反驳", e: "New evidence <b>refuted</b> the hypothesis." },
  { w: "reinforce", p: "/ˌriːɪnˈfɔːs/", m: "v. 加强，加固", e: "Steel plates <b>reinforce</b> the reactor wall." },
  { w: "resemble", p: "/rɪˈzembl/", m: "v. 类似，像", e: "The pilot plant <b>resembles</b> the full-scale one." },
  { w: "reside", p: "/rɪˈzaɪd/", m: "v. 居住；在于（reside in）", e: "The answer <b>resides in</b> the details." },
  { w: "resort", p: "/rɪˈzɔːt/", m: "n. 手段 v. 诉诸（resort to）", e: "Do not <b>resort to</b> guesswork." },
  { w: "restore", p: "/rɪˈstɔː/", m: "v. 恢复，修复", e: "They quickly <b>restored</b> the power supply." },
  { w: "retain", p: "/rɪˈteɪn/", m: "v. 保留，保持", e: "The gel <b>retains</b> moisture for weeks." },
  { w: "retrieve", p: "/rɪˈtriːv/", m: "v. 取回，检索", e: "They <b>retrieved</b> the data from the backup." },
  { w: "reverse", p: "/rɪˈvɜːs/", m: "v. 逆转，颠倒 n. 相反", e: "Better control can <b>reverse</b> the trend." },
  { w: "speculate", p: "/ˈspekjuleɪt/", m: "v. 推测；投机（speculate about/on）", e: "We can only <b>speculate about</b> the cause." },
  { w: "stem", p: "/stem/", m: "v. 源于（stem from） n. 茎", e: "The accident <b>stemmed from</b> poor maintenance." },
  { w: "subscribe", p: "/səbˈskraɪb/", m: "v. 订阅；赞同（subscribe to）", e: "Most scientists <b>subscribe to</b> this view." },
  { w: "suffice", p: "/səˈfaɪs/", m: "v. 足够（it suffices to say）", e: "A brief note will <b>suffice</b>." },
  { w: "summon", p: "/ˈsʌmən/", m: "v. 召唤；鼓起（summon up）", e: "She <b>summoned</b> the courage to ask questions." },
  { w: "sustain", p: "/səˈsteɪn/", m: "v. 维持，支撑", e: "The pump cannot <b>sustain</b> such a high load." },
  { w: "terminate", p: "/ˈtɜːmɪneɪt/", m: "v. 终止，结束", e: "They <b>terminated</b> the contract early." },
  { w: "trigger", p: "/ˈtrɪɡə/", m: "v. 触发，引发 n. 扳机", e: "A spark <b>triggered</b> the alarm." },
  { w: "undermine", p: "/ˌʌndəˈmaɪn/", m: "v. 削弱，暗中破坏", e: "Shortcuts <b>undermine</b> safety culture." },
  { w: "uphold", p: "/ʌpˈhəʊld/", m: "v. 维护，支持", e: "Inspectors <b>uphold</b> the highest standards." },
  { w: "verge", p: "/vɜːdʒ/", m: "n. 边缘（on the verge of）", e: "The company was on the <b>verge</b> of bankruptcy." },
  { w: "vulnerable", p: "/ˈvʌlnərəbl/", m: "adj. 脆弱的（vulnerable to）", e: "Carbon steel is <b>vulnerable to</b> corrosion." },
  { w: "aggregate", p: "/ˈæɡrɪɡət/", m: "n. 总数 adj. 总的 v. 聚集", e: "In the <b>aggregate</b>, savings were significant." },
  { w: "coherent", p: "/kəʊˈhɪərənt/", m: "adj. 连贯的，条理清楚的", e: "Her essay is clear and <b>coherent</b>." },
  { w: "diffuse", p: "/dɪˈfjuːz/", m: "v. 扩散 adj. 弥漫的", e: "Gas molecules <b>diffuse</b> through the membrane." },
  { w: "eloquent", p: "/ˈeləkwənt/", m: "adj. 雄辩的，有说服力的", e: "She gave an <b>eloquent</b> defense of the project." },
  { w: "abrupt", p: "/əˈbrʌpt/", m: "adj. 突然的；唐突的", e: "The <b>abrupt</b> shutdown damaged the compressor." },
  { w: "accord", p: "/əˈkɔːd/", m: "n. 协议 v. 一致（in accord with）", e: "The results are in <b>accord</b> with theory." },
  { w: "acknowledge", p: "/əkˈnɒlɪdʒ/", m: "v. 承认；致谢", e: "He <b>acknowledged</b> the error in the report." },
  { w: "acquaint", p: "/əˈkweɪnt/", m: "v. 使熟悉（be acquainted with）", e: "New workers are <b>acquainted with</b> the plant layout." },
  { w: "adequate", p: "/ˈædɪkwət/", m: "adj. 足够的；胜任的", e: "The cooling capacity is barely <b>adequate</b>." },
  { w: "administer", p: "/ədˈmɪnɪstə/", m: "v. 管理；执行，施行", e: "She <b>administers</b> the lab safety program." },
  { w: "aesthetic", p: "/iːsˈθetɪk/", m: "adj. 美学的，审美的", e: "The design balances function and <b>aesthetic</b> appeal." },
  { w: "affiliate", p: "/əˈfɪlieɪt/", m: "v. 使隶属（affiliate with）", e: "The institute is <b>affiliated with</b> the university." },
  { w: "affirm", p: "/əˈfɜːm/", m: "v. 断言，确认", e: "The data <b>affirms</b> our prediction." },
  { w: "agitate", p: "/ˈædʒɪteɪt/", m: "v. 搅动；煽动", e: "<b>Agitate</b> the solution before sampling." },
  { w: "alert", p: "/əˈlɜːt/", m: "adj. 警觉的 n. 警报", e: "Stay <b>alert</b> during the night shift." },
  { w: "allocate", p: "/ˈæləkeɪt/", m: "v. 分配，拨给", e: "They <b>allocated</b> more budget to safety." },
  { w: "alternate", p: "/ˈɔːltəneɪt/", m: "v. 交替 adj. 轮流的", e: "The two pumps <b>alternate</b> every week." },
  { w: "ambitious", p: "/æmˈbɪʃəs/", m: "adj. 有雄心的；艰巨的", e: "The carbon target is <b>ambitious</b> but achievable." },
  { w: "ample", p: "/ˈæmpl/", m: "adj. 充足的，丰富的", e: "There is <b>ample</b> evidence for the conclusion." },
  { w: "appeal", p: "/əˈpiːl/", m: "v./n. 呼吁；吸引力（appeal to）", e: "The campaign <b>appeals to</b> young engineers." },
  { w: "appraisal", p: "/əˈpreɪzl/", m: "n. 评价，评估", e: "The annual <b>appraisal</b> is next month." },
  { w: "appropriate", p: "/əˈprəʊpriət/", m: "adj. 恰当的，适宜的", e: "Choose the <b>appropriate</b> gasket material." },
  { w: "approximate", p: "/əˈprɒksɪmət/", m: "adj. 近似的 v. 接近", e: "The <b>approximate</b> cost is two million yuan." },
  { w: "apt", p: "/æpt/", m: "adj. 恰当的；易于…的（apt to）", e: "This warning is <b>apt</b> for all freshmen." },
  { w: "ascend", p: "/əˈsend/", m: "v. 上升，攀登", e: "Hot vapor <b>ascends</b> the column." },
  { w: "aspire", p: "/əˈspaɪə/", m: "v. 渴望，追求（aspire to）", e: "She <b>aspires to</b> a research career." },
  { w: "assault", p: "/əˈsɔːlt/", m: "n./v. 攻击，袭击", e: "Noise is a constant <b>assault</b> on hearing." },
  { w: "assemble", p: "/əˈsembl/", m: "v. 组装；集合", e: "They <b>assembled</b> the reactor on site." },
  { w: "assert", p: "/əˈsɜːt/", m: "v. 断言；维护（assert oneself）", e: "He <b>asserted</b> that the data was reliable." },
  { w: "asset", p: "/ˈæset/", m: "n. 资产；宝贵的人/物", e: "Fluency in English is a real <b>asset</b>." },
  { w: "assimilate", p: "/əˈsɪməleɪt/", m: "v. 吸收；同化", e: "Plants <b>assimilate</b> CO₂ into biomass." },
  { w: "associate", p: "/əˈsəʊʃieɪt/", m: "v. 联想；交往（associate with）", e: "We <b>associate</b> benzene with aromatic reactions." },
  { w: "assure", p: "/əˈʃʊə/", m: "v. 保证，使确信", e: "The supplier <b>assured</b> us of timely delivery." },
  { w: "astonish", p: "/əˈstɒnɪʃ/", m: "v. 使惊讶", e: "The yield <b>astonished</b> the whole team." },
  { w: "attribute", p: "/əˈtrɪbjuːt/", m: "v. 归因于（attribute to）n. 属性", e: "They <b>attributed</b> the loss to fouling." },
  { w: "audit", p: "/ˈɔːdɪt/", m: "n./v. 审计，稽查", e: "The safety <b>audit</b> found three hidden risks." },
  { w: "bare", p: "/beə/", m: "adj. 赤裸的；勉强的 v. 露出", e: "The wires were left <b>bare</b> and exposed." },
  { w: "barren", p: "/ˈbærən/", m: "adj. 贫瘠的；荒芜的", e: "The land was <b>barren</b> after decades of mining." },
  { w: "bias", p: "/ˈbaɪəs/", m: "n. 偏见 v. 使有偏见", e: "Avoid <b>bias</b> when selecting samples." },
  { w: "blend", p: "/blend/", m: "v./n. 混合，掺和", e: "<b>Blend</b> the two polymers at high temperature." },
  { w: "boast", p: "/bəʊst/", m: "v. 自夸；拥有（值得自豪之物）", e: "The campus <b>boasts</b> three pilot plants." },
  { w: "breakdown", p: "/ˈbreɪkdaʊn/", m: "n. 故障；分解；崩溃", e: "A pump <b>breakdown</b> halted production." },
  { w: "casualty", p: "/ˈkæʒuəlti/", m: "n. 伤亡人员", e: "The drill ended with zero <b>casualties</b>." },
  { w: "catastrophe", p: "/kəˈtæstrəfi/", m: "n. 大灾难", e: "Loss of cooling could cause a <b>catastrophe</b>." },
  { w: "cater", p: "/ˈkeɪtə/", m: "v. 迎合；提供（cater to）", e: "The course <b>caters to</b> beginners' needs." },
  { w: "caution", p: "/ˈkɔːʃn/", m: "n. 谨慎；警告 v. 提醒", e: "Handle perchloric acid with great <b>caution</b>." },
  { w: "cease", p: "/siːs/", m: "v. 停止，终止", e: "The reaction <b>ceased</b> once the feed stopped." },
  { w: "certify", p: "/ˈsɜːtɪfaɪ/", m: "v. 证明，认证", e: "The lab is <b>certified</b> to ISO 17025." },
  { w: "chronic", p: "/ˈkrɒnɪk/", m: "adj. 慢性的；长期的", e: "<b>Chronic</b> exposure to benzene harms health." },
  { w: "circulate", p: "/ˈsɜːkjəleɪt/", m: "v. 循环，流通", e: "Coolant <b>circulates</b> through the jacket." },
  { w: "cite", p: "/saɪt/", m: "v. 引用；传讯", e: "The paper <b>cites</b> forty references." },
  { w: "clamp", p: "/klæmp/", m: "v. 夹紧 n. 夹具", e: "<b>Clamp</b> the pipe before cutting it." },
  { w: "clarify", p: "/ˈklærəfaɪ/", m: "v. 澄清，阐明", e: "Could you <b>clarify</b> the last requirement?" },
  { w: "cling", p: "/klɪŋ/", m: "v. 紧贴；坚持（cling to）", e: "Droplets <b>cling to</b> the tower packing." },
  { w: "cognitive", p: "/ˈkɒɡnətɪv/", m: "adj. 认知的", e: "Sleep affects <b>cognitive</b> performance." },
  { w: "collapse", p: "/kəˈlæps/", m: "v./n. 倒塌；崩溃", e: "The tank <b>collapsed</b> under vacuum." },
  { w: "collide", p: "/kəˈlaɪd/", m: "v. 碰撞（collide with）", e: "Molecules <b>collide</b> millions of times a second." },
  { w: "commute", p: "/kəˈmjuːt/", m: "v. 通勤；减刑", e: "She <b>commutes</b> to the plant by bus." },
  { w: "comparable", p: "/ˈkɒmpərəbl/", m: "adj. 可比的（comparable to）", e: "The two catalysts are <b>comparable</b> in activity." },
  { w: "competent", p: "/ˈkɒmpɪtənt/", m: "adj. 胜任的，有能力的", e: "He is a <b>competent</b> process engineer." },
  { w: "complement", p: "/ˈkɒmplɪment/", m: "v. 补充 n. 补足物", e: "Theory and practice <b>complement</b> each other." },
  { w: "component", p: "/kəmˈpəʊnənt/", m: "n. 组成部分；零部件", e: "Each <b>component</b> was pressure-tested." },
  { w: "compound", p: "/ˈkɒmpaʊnd/", m: "n. 化合物 adj. 复合的", e: "The <b>compound</b> decomposes above 200°C." },
  { w: "comprehend", p: "/ˌkɒmprɪˈhend/", m: "v. 理解，领会", e: "Few students fully <b>comprehend</b> the derivation." },
  { w: "compress", p: "/kəmˈpres/", m: "v. 压缩", e: "The gas is <b>compressed</b> to 30 bar." },
  { w: "comprise", p: "/kəmˈpraɪz/", m: "v. 包含；由…组成", e: "The kit <b>comprises</b> five sensors." },
  { w: "conceal", p: "/kənˈsiːl/", m: "v. 隐藏，隐瞒", e: "He tried to <b>conceal</b> the defect from the auditor." },
  { w: "concede", p: "/kənˈsiːd/", m: "v. 承认；让步", e: "She <b>conceded</b> that the plan had risks." },
  { w: "condense", p: "/kənˈdens/", m: "v. 冷凝；浓缩", e: "Steam <b>condenses</b> in the shell side." },
  { w: "configuration", p: "/kənˌfɪɡəˈreɪʃn/", m: "n. 构型；配置", e: "Choose the right <b>configuration</b> of heat exchanger." },
  { w: "confine", p: "/kənˈfaɪn/", m: "v. 限制，局限", e: "Do not <b>confine</b> yourself to one method." },
  { w: "confront", p: "/kənˈfrʌnt/", m: "v. 面对，对抗", e: "Engineers <b>confront</b> trade-offs every day." },
  { w: "consensus", p: "/kənˈsensəs/", m: "n. 共识，一致", e: "The team reached a <b>consensus</b> quickly." },
  { w: "consent", p: "/kənˈsent/", m: "n./v. 同意，准许", e: "Written <b>consent</b> is required before sampling." },
  { w: "conserve", p: "/kənˈsɜːv/", m: "v. 节约，保护", e: "Recovering heat helps <b>conserve</b> energy." },
  { w: "consistent", p: "/kənˈsɪstənt/", m: "adj. 一致的；始终如一的", e: "The results are <b>consistent</b> with theory." },
  { w: "conspicuous", p: "/kənˈspɪkjuəs/", m: "adj. 显眼的，惹人注目的", e: "The leak left a <b>conspicuous</b> stain." },
  { w: "contempt", p: "/kənˈtempt/", m: "n. 轻视，蔑视", e: "He showed <b>contempt</b> for sloppy work." },
  { w: "contend", p: "/kənˈtend/", m: "v. 竞争；主张", e: "Several firms <b>contend</b> for the contract." },
  { w: "controversy", p: "/ˈkɒntrəvɜːsi/", m: "n. 争论，争议", e: "The new additive sparked <b>controversy</b>." },
  { w: "conventional", p: "/kənˈvenʃənl/", m: "adj. 常规的，传统的", e: "<b>Conventional</b> solvents are being replaced." },
  { w: "convert", p: "/kənˈvɜːt/", m: "v. 转变，转化（convert into）", e: "The unit <b>converts</b> heat into power." },
  { w: "conviction", p: "/kənˈvɪkʃn/", m: "n. 坚信；定罪", e: "She spoke with deep <b>conviction</b>." },
  { w: "coordinate", p: "/kəʊˈɔːdɪneɪt/", m: "v. 协调 n. 坐标", e: "Please <b>coordinate</b> with the maintenance crew." },
  { w: "correlate", p: "/ˈkɒrəleɪt/", m: "v. 相关（correlate with）", e: "Yield <b>correlates</b> strongly with temperature." },
  { w: "corrode", p: "/kəˈrəʊd/", m: "v. 腐蚀，侵蚀", e: "Chloride ions <b>corrode</b> stainless steel." },
  { w: "counterpart", p: "/ˈkaʊntəpɑːt/", m: "n. 对应的人/物", e: "Discuss this with your <b>counterpart</b> in QA." },
  { w: "counsel", p: "/ˈkaʊnsl/", m: "v. 劝告 n. 忠告", e: "She <b>counseled</b> patience during the audit." },
  { w: "cumulative", p: "/ˈkjuːmjələtɪv/", m: "adj. 累积的", e: "<b>Cumulative</b> errors can be fatal." },
  { w: "curriculum", p: "/kəˈrɪkjələm/", m: "n. 课程，课程体系", e: "The <b>curriculum</b> was revised this year." },
  { w: "decay", p: "/dɪˈkeɪ/", m: "v./n. 腐烂；衰变", e: "Radioactive isotopes <b>decay</b> over time." },
  { w: "decent", p: "/ˈdiːsnt/", m: "adj. 尚可的；体面的", e: "The plant pays a <b>decent</b> starting salary." },
  { w: "decline", p: "/dɪˈklaɪn/", m: "v. 下降；婉拒 n. 衰退", e: "Oil demand may <b>decline</b> after 2030." },
  { w: "defect", p: "/ˈdiːfekt/", m: "n. 缺陷 v. 叛逃", e: "The weld had a hidden <b>defect</b>." },
  { w: "deficient", p: "/dɪˈfɪʃnt/", m: "adj. 缺乏的（deficient in）", e: "The diet is <b>deficient in</b> vitamin D." },
  { w: "deficit", p: "/ˈdefɪsɪt/", m: "n. 赤字；不足", e: "The plant ran an energy <b>deficit</b> last year." },
  { w: "delegate", p: "/ˈdelɪɡət/", m: "v. 委派 n. 代表", e: "She <b>delegates</b> routine tasks to juniors." },
  { w: "delicate", p: "/ˈdelɪkət/", m: "adj. 精密的；微妙的", e: "The instrument is <b>delicate</b> and costly." },
  { w: "denial", p: "/dɪˈnaɪəl/", m: "n. 否认；拒绝", e: "His <b>denial</b> of the problem delayed repairs." },
  { w: "denounce", p: "/dɪˈnaʊns/", m: "v. 谴责，告发", e: "Regulators <b>denounced</b> the illegal discharge." },
  { w: "deplete", p: "/dɪˈpliːt/", m: "v. 耗尽，使枯竭", e: "Over-mining will <b>deplete</b> the ore reserves." },
  { w: "deposit", p: "/dɪˈpɒzɪt/", m: "n. 沉积物；押金 v. 沉积", e: "Scale <b>deposits</b> inside the boiler tubes." },
  { w: "depreciate", p: "/dɪˈpriːʃieɪt/", m: "v. 贬值；轻视", e: "The equipment <b>depreciates</b> by 10% a year." },
  { w: "derive", p: "/dɪˈraɪv/", m: "v. 源自；提取（derive from）", e: "Ethanol is <b>derived from</b> biomass." },
  { w: "despise", p: "/dɪˈspaɪz/", m: "v. 鄙视，看不起", e: "Do not <b>despise</b> small experiments." },
  { w: "detach", p: "/dɪˈtætʃ/", m: "v. 拆卸，分离（detach from）", e: "<b>Detach</b> the hose before servicing." },
  { w: "detect", p: "/dɪˈtekt/", m: "v. 察觉；检测", e: "Sensors <b>detect</b> traces of H₂S." },
  { w: "detrimental", p: "/ˌdetrɪˈmentl/", m: "adj. 有害的（detrimental to）", e: "Foam is <b>detrimental to</b> pump efficiency." },
  { w: "devise", p: "/dɪˈvaɪz/", m: "v. 设计，想出", e: "They <b>devised</b> a safer sampling route." },
  { w: "devote", p: "/dɪˈvəʊt/", m: "v. 奉献（devote to）", e: "He <b>devotes</b> weekends to research." },
  { w: "diagnose", p: "/ˈdaɪəɡnəʊz/", m: "v. 诊断", e: "Vibration data <b>diagnosed</b> the bearing fault." },
  { w: "differentiate", p: "/ˌdɪfəˈrenʃieɪt/", m: "v. 区分；求微分", e: "Learn to <b>differentiate</b> fault from noise." },
  { w: "diligent", p: "/ˈdɪlɪdʒənt/", m: "adj. 勤奋的", e: "She is a <b>diligent</b> note-taker." },
  { w: "dilute", p: "/daɪˈluːt/", m: "v. 稀释 adj. 稀的", e: "<b>Dilute</b> the acid before disposal." },
  { w: "diploma", p: "/dɪˈpləʊmə/", m: "n. 文凭，毕业证书", e: "The job requires a bachelor <b>diploma</b>." },
  { w: "disable", p: "/dɪˈseɪbl/", m: "v. 使丧失能力；禁用", e: "Never <b>disable</b> a safety interlock." },
  { w: "discard", p: "/dɪˈskɑːd/", m: "v. 丢弃", e: "<b>Discard</b> any cracked glassware." },
  { w: "discharge", p: "/dɪsˈtʃɑːdʒ/", m: "v./n. 排放；卸料；出院", e: "The plant <b>discharges</b> treated water." },
  { w: "discipline", p: "/ˈdɪsəplɪn/", m: "n. 学科；纪律 v. 训练", e: "Safety is a <b>discipline</b>, not a slogan." },
  { w: "discrete", p: "/dɪˈskriːt/", m: "adj. 离散的", e: "The model treats stages as <b>discrete</b> units." },
  { w: "dismiss", p: "/dɪsˈmɪs/", m: "v. 解散；解雇；摒弃", e: "Do not <b>dismiss</b> the warning light." },
  { w: "displace", p: "/dɪsˈpleɪs/", m: "v. 取代；置换", e: "Air is <b>displaced</b> by nitrogen padding." },
  { w: "disposal", p: "/dɪˈspəʊzl/", m: "n. 处置；处理（at one's disposal）", e: "Waste <b>disposal</b> follows strict rules." },
  { w: "dispose", p: "/dɪˈspəʊz/", m: "v. 处理（dispose of）", e: "Dispose of solvents in the labeled bin." },
  { w: "dispute", p: "/dɪˈspjuːt/", m: "n./v. 争论", e: "The two teams <b>disputed</b> the data." },
  { w: "disregard", p: "/ˌdɪsrɪˈɡɑːd/", m: "v./n. 无视，漠视", e: "He <b>disregarded</b> the permit limits." },
  { w: "disrupt", p: "/dɪsˈrʌpt/", m: "v. 扰乱，中断", e: "A storm <b>disrupted</b> the power supply." },
  { w: "dissolve", p: "/dɪˈzɒlv/", m: "v. 溶解；解散", e: "The salt <b>dissolves</b> quickly in hot water." },
  { w: "distill", p: "/dɪˈstɪl/", m: "v. 蒸馏", e: "We <b>distill</b> the crude into fractions." },
  { w: "distinct", p: "/dɪˈstɪŋkt/", m: "adj. 明显的；不同的", e: "Two <b>distinct</b> phases appeared in the flask." },
  { w: "distract", p: "/dɪˈstrækt/", m: "v. 使分心（distract from）", e: "Do not let noise <b>distract</b> the operator." },
  { w: "domain", p: "/dəˈmeɪn/", m: "n. 领域", e: "Thermodynamics is the <b>domain</b> of theory." },
  { w: "domestic", p: "/dəˈmestɪk/", m: "adj. 国内的；家用的", e: "<b>Domestic</b> demand for lithium is rising." },
  { w: "dominate", p: "/ˈdɒmɪneɪt/", m: "v. 支配，主导", e: "Distillation costs <b>dominate</b> the process." },
  { w: "donate", p: "/dəʊˈneɪt/", m: "v. 捐赠", e: "The firm <b>donates</b> lab kits to schools." },
  { w: "drawback", p: "/ˈdrɔːbæk/", m: "n. 缺点，弊端", e: "The main <b>drawback</b> is high energy use." },
  { w: "dread", p: "/dred/", m: "v./n. 畏惧", e: "Students <b>dread</b> the oral exam." },
  { w: "drift", p: "/drɪft/", m: "v./n. 漂移；趋势", e: "The sensor <b>drifted</b> by 2% per month." },
  { w: "dubious", p: "/ˈdjuːbiəs/", m: "adj. 怀疑的；可疑的", e: "The supplier's claims seemed <b>dubious</b>." },
  { w: "duplicate", p: "/ˈdjuːplɪkeɪt/", m: "v. 复制 adj. 完全相同的", e: "Try to <b>duplicate</b> the experiment exactly." },
  { w: "durable", p: "/ˈdjʊərəbl/", m: "adj. 耐用的，持久的", e: "PTFE gaskets are chemically <b>durable</b>." },
  { w: "dynamic", p: "/daɪˈnæmɪk/", m: "adj. 动态的；有活力的", e: "The model captures <b>dynamic</b> behavior well." },
  { w: "elicit", p: "/ɪˈlɪsɪt/", m: "v. 引出，诱出（elicit a response）", e: "The survey <b>elicited</b> honest feedback." },
  { w: "eligible", p: "/ˈelɪdʒəbl/", m: "adj. 有资格的（eligible for）", e: "Only seniors are <b>eligible for</b> the exam." },
  { w: "eliminate", p: "/ɪˈlɪmɪneɪt/", m: "v. 消除，淘汰", e: "Better design <b>eliminates</b> dead zones." },
  { w: "elite", p: "/ɪˈliːt/", m: "n. 精英 adj. 精英的", e: "She joined an <b>elite</b> research group." },
  { w: "embed", p: "/ɪmˈbed/", m: "v. 嵌入", e: "Sensors are <b>embedded</b> in the reactor wall." },
  { w: "embody", p: "/ɪmˈbɒdi/", m: "v. 体现，使具体化", e: "The plant <b>embodies</b> green design ideas." },
  { w: "embrace", p: "/ɪmˈbreɪs/", m: "v. 拥抱；欣然接受", e: "The industry <b>embraces</b> digital tools." },
  { w: "emerge", p: "/ɪˈmɜːdʒ/", m: "v. 出现；浮现（emerge from）", e: "New standards <b>emerged</b> after the accident." },
  { w: "eminent", p: "/ˈemɪnənt/", m: "adj. 杰出的，著名的", e: "An <b>eminent</b> chemist gave the lecture." },
  { w: "emit", p: "/ɪˈmɪt/", m: "v. 排放，发出", e: "Coal plants <b>emit</b> large amounts of CO₂." },
  { w: "empirical", p: "/ɪmˈpɪrɪkl/", m: "adj. 经验的，实证的", e: "The correlation is purely <b>empirical</b>." },
  { w: "enact", p: "/ɪˈnækt/", m: "v. 制定（法律）", e: "The city <b>enacted</b> stricter emission rules." },
  { w: "encompass", p: "/ɪnˈkʌmpəs/", m: "v. 包含，涵盖", e: "The course <b>encompasses</b> both theory and practice." },
  { w: "endorse", p: "/ɪnˈdɔːs/", m: "v. 认可，支持", e: "The committee <b>endorsed</b> the new method." },
  { w: "endow", p: "/ɪnˈdaʊ/", m: "v. 赋予；捐赠（be endowed with）", e: "The region is <b>endowed with</b> rich minerals." },
  { w: "endure", p: "/ɪnˈdjʊə/", m: "v. 忍受；持久", e: "The coating <b>endures</b> strong acids." },
  { w: "engage", p: "/ɪnˈɡeɪdʒ/", m: "v. 从事；吸引（engage in）", e: "Students <b>engage in</b> hands-on projects." },
  { w: "enlighten", p: "/ɪnˈlaɪtn/", m: "v. 启发，开导", e: "Her talk <b>enlightened</b> us on reactor safety." },
  { w: "enrich", p: "/ɪnˈrɪtʃ/", m: "v. 使丰富；浓缩", e: "Reading <b>enriches</b> your vocabulary." },
  { w: "entail", p: "/ɪnˈteɪl/", m: "v. 必然涉及，需要", e: "The upgrade <b>entails</b> a two-week shutdown." },
  { w: "enterprise", p: "/ˈentəpraɪz/", m: "n. 企业；事业心", e: "The <b>enterprise</b> employs 3,000 workers." },
  { w: "entitle", p: "/ɪnˈtaɪtl/", m: "v. 使有权利（be entitled to）", e: "Members are <b>entitled to</b> free training." },
  { w: "entity", p: "/ˈentəti/", m: "n. 实体", e: "Each subsidiary is a separate legal <b>entity</b>." },
  { w: "episode", p: "/ˈepɪsəʊd/", m: "n. 一段经历；插曲；剧集", e: "The outage was a brief <b>episode</b> in an stable year." },
  { w: "equivalent", p: "/ɪˈkwɪvələnt/", m: "adj. 等价的 n. 等价物", e: "One kWh is <b>equivalent to</b> 3.6 MJ." },
  { w: "eradicate", p: "/ɪˈrædɪkeɪt/", m: "v. 根除，消灭", e: "The program aims to <b>eradicate</b> unsafe habits." },
  { w: "erroneous", p: "/ɪˈrəʊniəs/", m: "adj. 错误的", e: "The report was based on <b>erroneous</b> data." },
  { w: "erupt", p: "/ɪˈrʌpt/", m: "v. 爆发；喷发", e: "Violence <b>erupted</b> after the verdict." },
  { w: "escalate", p: "/ˈeskəleɪt/", m: "v. 使升级，加剧", e: "The dispute <b>escalated</b> into a strike." },
  { w: "essence", p: "/ˈesns/", m: "n. 本质（in essence）", e: "In <b>essence</b>, distillation is selective boiling." },
  { w: "eternal", p: "/ɪˈtɜːnl/", m: "adj. 永恒的", e: "No <b>eternal</b> solution exists for corrosion." },
  { w: "ethic", p: "/ˈeθɪk/", m: "n. 伦理；道德准则", e: "Engineers follow a strict code of <b>ethics</b>." },
  { w: "evaluate", p: "/ɪˈvæljueɪt/", m: "v. 评估，评价", e: "Let us <b>evaluate</b> both designs fairly." },
  { w: "evaporate", p: "/ɪˈvæpəreɪt/", m: "v. 蒸发", e: "Solvent <b>evaporates</b> quickly in open trays." },
  { w: "evolve", p: "/ɪˈvɒlv/", m: "v. 演变，进化", e: "The process will <b>evolve</b> over the decade." },
  { w: "exaggerate", p: "/ɪɡˈzædʒəreɪt/", m: "v. 夸大，夸张", e: "Do not <b>exaggerate</b> your lab experience." },
  { w: "exceed", p: "/ɪkˈsiːd/", m: "v. 超过", e: "The pressure must not <b>exceed</b> 40 bar." },
  { w: "excel", p: "/ɪkˈsel/", m: "v. 擅长，胜过（excel in）", e: "She <b>excels in</b> process simulation." },
  { w: "excerpt", p: "/ˈeksɜːpt/", m: "n. 摘录，节选", e: "Read this <b>excerpt</b> from the safety code." },
  { w: "excessive", p: "/ɪkˈsesɪv/", m: "adj. 过度的，过多的", e: "<b>Excessive</b> heat deforms the gasket." },
  { w: "exclaim", p: "/ɪkˈskleɪm/", m: "v. 呼喊，惊叫", e: "\"It works!\" she <b>exclaimed</b>." },
  { w: "exclusive", p: "/ɪkˈskluːsɪv/", m: "adj. 独有的；排他的", e: "The patent grants <b>exclusive</b> rights for 20 years." },
  { w: "execute", p: "/ˈeksɪkjuːt/", m: "v. 执行；实施", e: "The plan was <b>executed</b> on schedule." },
  { w: "exemplify", p: "/ɪɡˈzemplɪfaɪ/", m: "v. 例证，是…的典型", e: "This plant <b>exemplifies</b> modern safety culture." },
  { w: "exhaust", p: "/ɪɡˈzɔːst/", m: "v. 耗尽 n. 废气", e: "The purge <b>exhausts</b> the trapped vapor." },
  { w: "exhibit", p: "/ɪɡˈzɪbɪt/", m: "v. 展现，显示 n. 展品", e: "The alloy <b>exhibits</b> excellent strength." },
  { w: "exotic", p: "/ɪɡˈzɒtɪk/", m: "adj. 外来的；奇异的", e: "The lab tests <b>exotic</b> catalysts." },
  { w: "expel", p: "/ɪkˈspel/", m: "v. 排出；开除", e: "The vent <b>expels</b> inert gas overhead." },
  { w: "expertise", p: "/ˌekspɜːˈtiːz/", m: "n. 专业知识，专长", e: "Her <b>expertise</b> covers separation processes." },
  { w: "explicit", p: "/ɪkˈsplɪsɪt/", m: "adj. 明确的，清楚的", e: "The manual gives <b>explicit</b> instructions." },
  { w: "exploit", p: "/ɪkˈsplɔɪt/", m: "v. 利用；开发；剥削", e: "We can <b>exploit</b> waste heat for heating." },
  { w: "expose", p: "/ɪkˈspəʊz/", m: "v. 暴露；揭露（expose to）", e: "Workers are <b>exposed to</b> dust and noise." },
  { w: "exquisite", p: "/ɪkˈskwɪzɪt/", m: "adj. 精美的；敏锐的", e: "The glassware shows <b>exquisite</b> workmanship." },
  { w: "extinct", p: "/ɪkˈstɪŋkt/", m: "adj. 灭绝的", e: "Some species are nearly <b>extinct</b>." },
  { w: "extinguish", p: "/ɪkˈstɪŋɡwɪʃ/", m: "v. 扑灭，熄灭", e: "CO₂ systems <b>extinguish</b> fires fast." },
  { w: "extract", p: "/ɪkˈstrækt/", m: "v. 提取 n. 提出物", e: "Solvent is used to <b>extract</b> the oil." },
  { w: "extravagant", p: "/ɪkˈstrævəɡənt/", m: "adj. 奢侈的；过度的", e: "The proposal seemed <b>extravagant</b> for a pilot study." },
  { w: "fabricate", p: "/ˈfæbrɪkeɪt/", m: "v. 制造；捏造", e: "They <b>fabricate</b> custom flanges in-house." },
  { w: "faculty", p: "/ˈfæklti/", m: "n. 全体教员；才能", e: "The <b>faculty</b> voted on the new syllabus." },
  { w: "fatal", p: "/ˈfeɪtl/", m: "adj. 致命的", e: "One wrong valve line can prove <b>fatal</b>." },
  { w: "fatigue", p: "/fəˈtiːɡ/", m: "n. 疲劳 v. 使疲劳", e: "Metal <b>fatigue</b> cracked the shaft." },
  { w: "feeble", p: "/ˈfiːbl/", m: "adj. 微弱的，无力的", e: "The signal was too <b>feeble</b> to read." },
  { w: "fertile", p: "/ˈfɜːtaɪl/", m: "adj. 肥沃的；富有创造力的", e: "The valley has <b>fertile</b> farmland." },
  { w: "fierce", p: "/fɪəs/", m: "adj. 激烈的；猛烈的", e: "Competition for the post is <b>fierce</b>." },
  { w: "filter", p: "/ˈfɪltə/", m: "n. 过滤器 v. 过滤", e: "Pass the slurry through a <b>filter</b>." },
  { w: "finite", p: "/ˈfaɪnaɪt/", m: "adj. 有限的", e: "Oil is a <b>finite</b> resource." },
  { w: "flourish", p: "/ˈflʌrɪʃ/", m: "v. 繁荣，兴旺", e: "Biotech will <b>flourish</b> this decade." },
  { w: "flush", p: "/flʌʃ/", m: "v. 冲洗 n. 脸红", e: "<b>Flush</b> the line with nitrogen first." },
  { w: "fossil", p: "/ˈfɒsl/", m: "n. 化石 adj. 化石的", e: "<b>Fossil</b> fuels still dominate the mix." },
  { w: "fraud", p: "/frɔːd/", m: "n. 欺诈", e: "Data <b>fraud</b> ends careers instantly." },
  { w: "friction", p: "/ˈfrɪkʃn/", m: "n. 摩擦；冲突", e: "<b>Friction</b> losses raise the pumping cost." },
  { w: "fringe", p: "/frɪndʒ/", m: "n. 边缘 adj. 次要的", e: "The idea was once on the <b>fringe</b> of science." },
  { w: "frustrate", p: "/frʌˈstreɪt/", m: "v. 使沮丧，挫败", e: "Unstable runs <b>frustrated</b> the team." },
  { w: "fulfill", p: "/fʊlˈfɪl/", m: "v. 履行；满足", e: "The plant <b>fulfills</b> all emission limits." },
  { w: "fundamental", p: "/ˌfʌndəˈmentl/", m: "adj. 根本的，基础的 n. 基础", e: "Mass balance is <b>fundamental</b> to design." },
  { w: "futile", p: "/ˈfjuːtaɪl/", m: "adj. 徒劳的", e: "Arguing with data is <b>futile</b>." },
  { w: "gamble", p: "/ˈɡæmbl/", m: "v./n. 赌博，冒险", e: "Skipping tests is a <b>gamble</b> with safety." },
  { w: "generalize", p: "/ˈdʒenrəlaɪz/", m: "v. 概括；推广", e: "Do not <b>generalize</b> from one trial." },
  { w: "generate", p: "/ˈdʒenəreɪt/", m: "v. 产生，引起", e: "The turbine can <b>generate</b> 300 kW." },
  { w: "genetic", p: "/dʒəˈnetɪk/", m: "adj. 基因的，遗传的", e: "<b>Genetic</b> engineering reshaped biotech." },
  { w: "genuine", p: "/ˈdʒenjuɪn/", m: "adj. 真诚的；真正的", e: "The certificate is <b>genuine</b>." },
  { w: "gigantic", p: "/dʒaɪˈɡæntɪk/", m: "adj. 巨大的", e: "A <b>gigantic</b> compressor dominates the hall." },
  { w: "gloomy", p: "/ˈɡluːmi/", m: "adj. 阴暗的；悲观的", e: "The outlook seemed <b>gloomy</b> at first." },
  { w: "grant", p: "/ɡrɑːnt/", m: "v. 授予；同意 n. 拨款", e: "The fund <b>granted</b> money for the pilot." },
  { w: "graphic", p: "/ˈɡræfɪk/", m: "adj. 生动的；图表的 n. 图表", e: "The report uses <b>graphic</b> charts." },
  { w: "gratitude", p: "/ˈɡrætɪtjuːd/", m: "n. 感激", e: "She expressed <b>gratitude</b> to her mentor." },
  { w: "gravity", p: "/ˈɡrævəti/", m: "n. 重力；严重性", e: "<b>Gravity</b> drives the drain line." },
  { w: "grief", p: "/ɡriːf/", m: "n. 悲伤", e: "The accident caused deep <b>grief</b>." },
  { w: "grim", p: "/ɡrɪm/", m: "adj. 严峻的；冷酷的", e: "The safety record looks <b>grim</b>." },
  { w: "grind", p: "/ɡraɪnd/", m: "v. 磨，碾磨", e: "The mill <b>grinds</b> limestone to powder." },
  { w: "gross", p: "/ɡrəʊs/", m: "adj. 总的；严重的", e: "<b>Gross</b> output doubled in five years." },
  { w: "halt", p: "/hɔːlt/", m: "v./n. 停止", e: "The line came to a <b>halt</b> at noon." },
  { w: "harsh", p: "/hɑːʃ/", m: "adj. 严厉的；恶劣的", e: "The catalyst works in <b>harsh</b> conditions." },
  { w: "hatch", p: "/hætʃ/", m: "v. 孵化 n. 舱口", e: "Open the <b>hatch</b> before entering." },
  { w: "haul", p: "/hɔːl/", m: "v. 拖运 n. 运输距离", e: "Trucks <b>haul</b> the product to the port." },
  { w: "hectic", p: "/ˈhektɪk/", m: "adj. 忙乱的", e: "Startup week was <b>hectic</b> but exciting." },
  { w: "heir", p: "/eə/", m: "n. 继承人", e: "She is the <b>heir</b> to the family firm." },
  { w: "hemisphere", p: "/ˈhemɪsfɪə/", m: "n. 半球", e: "Seasons differ between <b>hemispheres</b>." },
  { w: "heritage", p: "/ˈherɪtɪdʒ/", m: "n. 遗产，传统", e: "Green chemistry is our shared <b>heritage</b>." },
  { w: "hesitant", p: "/ˈhezɪtənt/", m: "adj. 犹豫的（hesitant about）", e: "He was <b>hesitant</b> about signing." },
  { w: "hierarchy", p: "/ˈhaɪərɑːki/", m: "n. 等级体系", e: "The lab has a flat <b>hierarchy</b>." },
  { w: "highlight", p: "/ˈhaɪlaɪt/", m: "v. 强调 n. 亮点", e: "The report <b>highlights</b> three risks." },
  { w: "homogeneous", p: "/ˌhɒməˈdʒiːniəs/", m: "adj. 均匀的，同质的", e: "Keep the feed <b>homogeneous</b>." },
  { w: "horizon", p: "/həˈraɪzn/", m: "n. 地平线；视野（broaden one's horizon）", e: "Exchange programs <b>broaden horizons</b>." },
  { w: "hostile", p: "/ˈhɒstaɪl/", m: "adj. 敌意的；不利的（hostile to）", e: "Deserts are <b>hostile</b> to most equipment." },
  { w: "humidity", p: "/hjuːˈmɪdəti/", m: "n. 湿度", e: "Store the reagent at low <b>humidity</b>." },
  { w: "hypothesis", p: "/haɪˈpɒθəsɪs/", m: "n. 假设，假说", e: "The data support the first <b>hypothesis</b>." },
  { w: "identical", p: "/aɪˈdentɪkl/", m: "adj. 完全相同的（identical to）", e: "The two samples are practically <b>identical</b>." },
  { w: "idle", p: "/ˈaɪdl/", m: "adj. 空闲的 v. 空转", e: "Do not let the pump run <b>idle</b> for long." },
  { w: "ignite", p: "/ɪɡˈnaɪt/", m: "v. 点燃，着火", e: "A stray spark <b>ignited</b> the vapor." },
  { w: "ignorance", p: "/ˈɪɡnərəns/", m: "n. 无知（out of ignorance）", e: "Accidents often stem from <b>ignorance</b>." },
  { w: "illusion", p: "/ɪˈluːʒn/", m: "n. 错觉，幻觉", e: "Low reading does not equal low risk — that is an <b>illusion</b>." },
  { w: "imminent", p: "/ˈɪmɪnənt/", m: "adj. 即将来临的", e: "A storm is <b>imminent</b>; secure the site." },
  { w: "immune", p: "/ɪˈmjuːn/", m: "adj. 免疫的；不受影响的（immune to）", e: "No plant is <b>immune to</b> human error." },
  { w: "impair", p: "/ɪmˈpeə/", m: "v. 损害，削弱", e: "Fouling <b>impairs</b> heat transfer." },
  { w: "impartial", p: "/ɪmˈpɑːʃl/", m: "adj. 公正的", e: "The audit must stay <b>impartial</b>." },
  { w: "implement", p: "/ˈɪmplɪment/", m: "v. 实施，执行 n. 工具", e: "The firm will <b>implement</b> the new standard in May." },
  { w: "implicit", p: "/ɪmˈplɪsɪt/", m: "adj. 含蓄的；内含的", e: "Trust is <b>implicit</b> in teamwork." },
  { w: "impulse", p: "/ˈɪmpʌls/", m: "n. 冲动；脉冲", e: "Avoid acting on <b>impulse</b> in the control room." },
  { w: "incline", p: "/ɪnˈklaɪn/", m: "v. 倾向于（be inclined to）", e: "She is <b>inclined to</b> choose process design." },
  { w: "incorporate", p: "/ɪnˈkɔːpəreɪt/", m: "v. 纳入，合并（incorporate into）", e: "Safety is <b>incorporated into</b> every design step." },
  { w: "incur", p: "/ɪnˈkɜː/", m: "v. 招致，引起", e: "Late delivery <b>incurred</b> heavy penalties." },
  { w: "indefinite", p: "/ɪnˈdefɪnət/", m: "adj. 不确定的，无限期的", e: "The shutdown may last an <b>indefinite</b> period." },
  { w: "indifferent", p: "/ɪnˈdɪfrənt/", m: "adj. 冷漠的（indifferent to）", e: "Do not stay <b>indifferent to</b> near-misses." },
  { w: "indignant", p: "/ɪnˈdɪɡnənt/", m: "adj. 愤慨的", e: "Residents were <b>indignant</b> about the leak." },
  { w: "indispensable", p: "/ˌɪndɪˈspensəbl/", m: "adj. 不可或缺的（indispensable to）", e: "Lab notebooks are <b>indispensable</b> to research." },
  { w: "induce", p: "/ɪnˈdjuːs/", m: "v. 诱导；引起", e: "Stress can <b>induce</b> cracks in the liner." },
  { w: "inertia", p: "/ɪˈnɜːʃə/", m: "n. 惯性；惰性", e: "Bureaucratic <b>inertia</b> slows every reform." },
  { w: "inevitable", p: "/ɪnˈevɪtəbl/", m: "adj. 不可避免的", e: "Some downtime is <b>inevitable</b>." },
  { w: "infectious", p: "/ɪnˈfekʃəs/", m: "adj. 传染的", e: "The lab handles <b>infectious</b> samples." },
  { w: "inferior", p: "/ɪnˈfɪəriə/", m: "adj. 较差的（inferior to）", e: "The clone proved <b>inferior to</b> the original." },
  { w: "infinite", p: "/ˈɪnfɪnət/", m: "adj. 无限的", e: "Theory assumes an <b>infinite</b> heat sink." },
  { w: "inflate", p: "/ɪnˈfleɪt/", m: "v. 使膨胀；通胀", e: "Do not <b>inflate</b> the tire beyond 8 bar." },
  { w: "inflict", p: "/ɪnˈflɪkt/", m: "v. 施加（inflict on）", e: "The outage <b>inflicted</b> heavy losses on the mill." },
  { w: "ingenious", p: "/ɪnˈdʒiːniəs/", m: "adj. 巧妙的，天才的", e: "That is an <b>ingenious</b> pipe-routing fix." },
  { w: "inhabit", p: "/ɪnˈhæbɪt/", m: "v. 居住于", e: "Few species <b>inhabit</b> the acidic lake." },
  { w: "inherit", p: "/ɪnˈherɪt/", m: "v. 继承", e: "She <b>inherited</b> the project from a former intern." },
  { w: "inhibit", p: "/ɪnˈhɪbɪt/", m: "v. 抑制", e: "Sulfur <b>inhibits</b> the catalyst activity." },
  { w: "initiate", p: "/ɪˈnɪʃieɪt/", m: "v. 发起，启动", e: "The operator <b>initiated</b> the emergency stop." },
  { w: "inject", p: "/ɪnˈdʒekt/", m: "v. 注入，注射", e: "<b>Inject</b> the inhibitor upstream of the pump." },
  { w: "insight", p: "/ˈɪnsaɪt/", m: "n. 洞察，深刻见解", e: "The data offer a fresh <b>insight</b>." },
  { w: "inspect", p: "/ɪnˈspekt/", m: "v. 检查，视察", e: "Engineers <b>inspect</b> the welds yearly." },
  { w: "insufficient", p: "/ˌɪnsəˈfɪʃnt/", m: "adj. 不足的", e: "The data set is <b>insufficient</b> for conclusions." },
  { w: "integrate", p: "/ˈɪntɪɡreɪt/", m: "v. 整合（integrate into）", e: "We must <b>integrate</b> safety into design." },
  { w: "intellect", p: "/ˈɪntəlekt/", m: "n. 智力，才智", e: "The work rewards both patience and <b>intellect</b>." },
  { w: "intense", p: "/ɪnˈtens/", m: "adj. 强烈的；紧张的", e: "The reaction releases <b>intense</b> heat." },
  { w: "intent", p: "/ɪnˈtent/", m: "n. 意图 adj. 专注的", e: "He visited the lab with clear <b>intent</b>." },
  { w: "interact", p: "/ˌɪntərˈækt/", m: "v. 相互作用（interact with）", e: "The drug may <b>interact with</b> the solvent." },
  { w: "interim", p: "/ˈɪntərɪm/", m: "adj. 临时的 n. 过渡期", e: "An <b>interim</b> report is due in June." },
  { w: "intermittent", p: "/ˌɪntəˈmɪtnt/", m: "adj. 间歇的", e: "The sensor gave <b>intermittent</b> readings." },
  { w: "intimate", p: "/ˈɪntɪmət/", m: "adj. 亲密的；私下的；精通的（intimate knowledge of）", e: "She has <b>intimate</b> knowledge of the unit." },
  { w: "intrigue", p: "/ɪnˈtriːɡ/", m: "v. 激起兴趣 n. 阴谋", e: "The anomaly <b>intrigued</b> the researchers." },
  { w: "invade", p: "/ɪnˈveɪd/", m: "v. 侵入，侵略", e: "Moisture <b>invaded</b> the control cabinet." },
  { w: "invaluable", p: "/ɪnˈvæljuəbl/", m: "adj. 极宝贵的", e: "Field experience is <b>invaluable</b>." },
  { w: "invariably", p: "/ɪnˈveəriəbli/", m: "adv. 始终，总是", e: "Shortcuts <b>invariably</b> cost more later." },
  { w: "inventory", p: "/ˈɪnvəntri/", m: "n. 库存，清单", e: "Check the spare-parts <b>inventory</b> monthly." },
  { w: "inverse", p: "/ˌɪnˈvɜːs/", m: "adj. 相反的；反向的 n. 反面", e: "Cost moves in <b>inverse</b> proportion to scale." },
  { w: "irrigate", p: "/ˈɪrɪɡeɪt/", m: "v. 灌溉", e: "The plant <b>irrigates</b> the nearby fields." },
  { w: "irritate", p: "/ˈɪrɪteɪt/", m: "v. 激怒；刺激", e: "Ammonia <b>irritates</b> the eyes." },
  { w: "isolate", p: "/ˈaɪsəleɪt/", m: "v. 隔离；使孤立", e: "The system can <b>isolate</b> each reactor train." },
  { w: "justify", p: "/ˈdʒʌstɪfaɪ/", m: "v. 证明…正当；为…辩护", e: "The savings <b>justify</b> the upgrade." },
  { w: "keen", p: "/kiːn/", m: "adj. 热衷的；敏锐的（keen on）", e: "She is <b>keen on</b> process optimization." },
  { w: "label", p: "/ˈleɪbl/", m: "n. 标签 v. 贴标签", e: "Read the <b>label</b> before opening any drum." },
  { w: "latent", p: "/ˈleɪtnt/", m: "adj. 潜在的，隐藏的", e: "The fault lay <b>latent</b> for months." },
  { w: "latitude", p: "/ˈlætɪtjuːd/", m: "n. 纬度；回旋余地", e: "The code allows some <b>latitude</b> in design." },
  { w: "layout", p: "/ˈleɪaʊt/", m: "n. 布局，布置", e: "A compact <b>layout</b> cuts piping costs." },
  { w: "leakage", p: "/ˈliːkɪdʒ/", m: "n. 泄漏", e: "Daily checks prevent <b>leakage</b>." },
  { w: "leverage", p: "/ˈliːvərɪdʒ/", m: "v. 利用 n. 杠杆；优势", e: "<b>Leverage</b> existing data before new tests." },
  { w: "liable", p: "/ˈlaɪəbl/", m: "adj. 易于…的；有责任的（liable to/for）", e: "Old seals are <b>liable to</b> crack." },
  { w: "liberal", p: "/ˈlɪbərəl/", m: "adj. 开放的；人文的；自由的", e: "A <b>liberal</b> arts background helps writing." },
  { w: "literal", p: "/ˈlɪtərəl/", m: "adj. 字面的；逐字的", e: "The <b>literal</b> meaning differs from the usage." },
  { w: "lucrative", p: "/ˈluːkrətɪv/", m: "adj. 赚钱的", e: "Patents made the process highly <b>lucrative</b>." },
  { w: "lure", p: "/lʊə/", m: "v./n. 引诱", e: "High pay alone should not <b>lure</b> you." },
  { w: "magnitude", p: "/ˈmæɡnɪtjuːd/", m: "n. 大小；量级；重要性", e: "The <b>magnitude</b> of the pressure drop surprised us." },
  { w: "maintain", p: "/meɪnˈteɪn/", m: "v. 维持；保养；主张", e: "Operators <b>maintain</b> the reactor at 350 °C." },
  { w: "mandatory", p: "/ˈmændətəri/", m: "adj. 强制的，义务的", e: "Safety training is <b>mandatory</b> for all new staff." },
  { w: "manifest", p: "/ˈmænɪfest/", m: "v. 显示 adj. 明显的", e: "Corruption problems <b>manifest</b> themselves slowly." },
  { w: "manipulate", p: "/məˈnɪpjuleɪt/", m: "v. 操纵；巧妙处理", e: "Robots <b>manipulate</b> the sample vials." },
  { w: "marginal", p: "/ˈmɑːdʒɪnl/", m: "adj. 边缘的；微小的", e: "The upgrade brought only a <b>marginal</b> gain." },
  { w: "meditate", p: "/ˈmedɪteɪt/", m: "v. 沉思；冥想", e: "He <b>meditated</b> on the causes of the failure." },
  { w: "merge", p: "/mɜːdʒ/", m: "v. 合并，融合", e: "Two streams <b>merge</b> before the distillation column." },
  { w: "merit", p: "/ˈmerɪt/", m: "n. 优点；价值 v. 值得", e: "Each proposal has its own <b>merits</b>." },
  { w: "metaphor", p: "/ˈmetəfə/", m: "n. 隐喻，比喻", e: "The textbook uses a pump <b>metaphor</b> to explain voltage." },
  { w: "meticulous", p: "/məˈtɪkjələs/", m: "adj. 一丝不苟的", e: "<b>Meticulous</b> record-keeping saved the audit." },
  { w: "migrate", p: "/maɪˈɡreɪt/", m: "v. 迁移；迁徙", e: "Data <b>migrates</b> to the cloud every night." },
  { w: "mimic", p: "/ˈmɪmɪk/", m: "v. 模仿", e: "The model <b>mimics</b> real plant behavior." },
  { w: "moderate", p: "/ˈmɒdərət/", m: "adj. 中等的 v. 缓和", e: "Keep the reaction at a <b>moderate</b> temperature." },
  { w: "momentum", p: "/məˈmentəm/", m: "n. 动力；动量", e: "The project gained <b>momentum</b> after the pilot test." },
  { w: "monitor", p: "/ˈmɒnɪtə/", m: "v./n. 监测；监视器", e: "Sensors <b>monitor</b> emissions around the clock." },
  { w: "monopoly", p: "/məˈnɒpəli/", m: "n. 垄断", e: "The firm once held a <b>monopoly</b> on catalyst supply." },
  { w: "mundane", p: "/mʌnˈdeɪn/", m: "adj. 平凡的，单调的", e: "Daily logging feels <b>mundane</b> but prevents errors." },
  { w: "municipal", p: "/mjuːˈnɪsɪpl/", m: "adj. 市政的", e: "The <b>municipal</b> plant treats 300,000 tons of wastewater daily." },
  { w: "multiple", p: "/ˈmʌltɪpl/", m: "adj. 多重的 n. 倍数", e: "The alarm has <b>multiple</b> backup triggers." },
  { w: "multitude", p: "/ˈmʌltɪtjuːd/", m: "n. 大量；群众", e: "A <b>multitude</b> of factors affects the yield." },
  { w: "motive", p: "/ˈməʊtɪv/", m: "n. 动机 adj. 发动的", e: "Profit was not the only <b>motive</b> for the research." },
  { w: "modify", p: "/ˈmɒdɪfaɪ/", m: "v. 修改，改进", e: "Engineers <b>modified</b> the pipeline routing." },
  { w: "naive", p: "/naɪˈiːv/", m: "adj. 天真的，幼稚的", e: "It is <b>naive</b> to expect zero risk in a plant." },
  { w: "narrative", p: "/ˈnærətɪv/", m: "n. 叙述 adj. 叙事的", e: "The report tells a clear <b>narrative</b> of the incident." },
  { w: "negotiate", p: "/nɪˈɡəʊʃieɪt/", m: "v. 谈判，协商", e: "The team <b>negotiated</b> a longer delivery window." },
  { w: "notable", p: "/ˈnəʊtəbl/", m: "adj. 显著的 n. 名人", e: "A <b>notable</b> drop in energy use followed the retrofit." },
  { w: "notion", p: "/ˈnəʊʃn/", m: "n. 观念，概念", e: "The <b>notion</b> of a circular economy is now mainstream." },
  { w: "nourish", p: "/ˈnʌrɪʃ/", m: "v. 滋养，培养", e: "Good habits <b>nourish</b> long-term learning." },
  { w: "novel", p: "/ˈnɒvl/", m: "adj. 新颖的 n. 小说", e: "The lab tested a <b>novel</b> membrane material." },
  { w: "numb", p: "/nʌm/", m: "adj. 麻木的 v. 使麻木", e: "Cold hands went <b>numb</b> during the outdoor survey." },
  { w: "obligation", p: "/ˌɒblɪˈɡeɪʃn/", m: "n. 义务，责任", e: "The contract imposes an <b>obligation</b> to report leaks." },
  { w: "obsolete", p: "/ˈɒbsəliːt/", m: "adj. 过时的，废弃的", e: "The old DCS became <b>obsolete</b> after 20 years." },
  { w: "obstacle", p: "/ˈɒbstəkl/", m: "n. 障碍", e: "Funding remains the main <b>obstacle</b> to the upgrade." },
  { w: "obstruct", p: "/əbˈstrʌkt/", m: "v. 阻塞，妨碍", e: "Scales <b>obstruct</b> the narrow tube section." },
  { w: "ominous", p: "/ˈɒmɪnəs/", m: "adj. 不祥的，预兆的", e: "An <b>ominous</b> rumble came from the compressor." },
  { w: "opponent", p: "/əˈpəʊnənt/", m: "n. 反对者；对手", e: "<b>Opponents</b> of the project cited water pollution." },
  { w: "optical", p: "/ˈɒptɪkl/", m: "adj. 光学的", e: "An <b>optical</b> sensor tracks turbidity in real time." },
  { w: "orbit", p: "/ˈɔːbɪt/", m: "n. 轨道 v. 环绕", e: "The satellite <b>orbits</b> Earth twice a day." },
  { w: "outbreak", p: "/ˈaʊtbreɪk/", m: "n. 爆发，突然蔓延", e: "The plant contained the <b>outbreak</b> of foam within hours." },
  { w: "outset", p: "/ˈaʊtset/", m: "n. 开始，开端", e: "Define the scope at the <b>outset</b> of the study." },
  { w: "overlap", p: "/ˌəʊvəˈlæp/", m: "v./n. 重叠", e: "The two shifts <b>overlap</b> by 30 minutes." },
  { w: "overwhelm", p: "/ˌəʊvəˈwelm/", m: "v. 淹没；压垮", e: "Demand <b>overwhelmed</b> the aging production line." },
  { w: "obtain", p: "/əbˈteɪn/", m: "v. 获得", e: "Pure crystals were <b>obtained</b> by slow cooling." },
  { w: "occupy", p: "/ˈɒkjupaɪ/", m: "v. 占据；使忙碌", e: "Storage tanks <b>occupy</b> the northern plot." },
  { w: "obsession", p: "/əbˈseʃn/", m: "n. 痴迷，执念", e: "His <b>obsession</b> with precision made the data reliable." },
  { w: "paradox", p: "/ˈpærədɒks/", m: "n. 悖论；矛盾的事", e: "It is a <b>paradox</b> that safer plants can feel riskier." },
  { w: "parallel", p: "/ˈpærəlel/", m: "adj. 平行的；类似的 n. 平行线", e: "Two <b>parallel</b> trains run through the same column." },
  { w: "paramount", p: "/ˈpærəmaʊnt/", m: "adj. 至高无上的", e: "Safety is of <b>paramount</b> importance in design." },
  { w: "pave", p: "/peɪv/", m: "v. 铺路（pave the way for）", e: "The pilot run <b>paved the way for</b> full production." },
  { w: "peculiar", p: "/pɪˈkjuːliə/", m: "adj. 特有的；奇怪的", e: "A <b>peculiar</b> smell signaled a leaking valve." },
  { w: "pension", p: "/ˈpenʃn/", m: "n. 养老金，退休金", e: "The company tops up the state <b>pension</b>." },
  { w: "perceive", p: "/pəˈsiːv/", m: "v. 感知，察觉", e: "Operators <b>perceive</b> small changes in noise first." },
  { w: "persist", p: "/pəˈsɪst/", m: "v. 坚持；持续存在", e: "The fouling problem <b>persisted</b> despite cleaning." },
  { w: "perspective", p: "/pəˈspektɪv/", m: "n. 视角；观点", e: "From a cost <b>perspective</b>, recycling wins." },
  { w: "pertinent", p: "/ˈpɜːtɪnənt/", m: "adj. 相关的，切题的", e: "Only <b>pertinent</b> data go into the final report." },
  { w: "pessimistic", p: "/ˌpesɪˈmɪstɪk/", m: "adj. 悲观的", e: "Do not be <b>pessimistic</b> about the job market." },
  { w: "phenomenon", p: "/fəˈnɒmɪnən/", m: "n. 现象", e: "Cavitation is a well-known <b>phenomenon</b> in pumps." },
  { w: "pioneer", p: "/ˌpaɪəˈnɪə/", m: "v. 开创 n. 先驱", e: "The group <b>pioneered</b> continuous crystallization." },
  { w: "plausible", p: "/ˈplɔːzəbl/", m: "adj. 貌似合理的", e: "Her explanation sounds <b>plausible</b> but lacks proof." },
  { w: "pledge", p: "/pledʒ/", m: "v./n. 承诺，保证", e: "The plant <b>pledged</b> to halve emissions by 2030." },
  { w: "plunge", p: "/plʌndʒ/", m: "v./n. 骤降；跳入", e: "Output took a sudden <b>plunge</b> in winter." },
  { w: "ponder", p: "/ˈpɒndə/", m: "v. 思考，掂量", e: "The panel <b>pondered</b> the risk of scaling up." },
  { w: "portray", p: "/pɔːˈtreɪ/", m: "v. 描绘，刻画", e: "The article <b>portrays</b> chemists as problem-solvers." },
  { w: "potent", p: "/ˈpəʊtnt/", m: "adj. 强有力的；有效的", e: "A <b>potent</b> catalyst cut the reaction time in half." },
  { w: "precise", p: "/prɪˈsaɪs/", m: "adj. 精确的", e: "Flow meters need <b>precise</b> calibration." },
  { w: "predecessor", p: "/ˈpriːdəsesə/", m: "n. 前任；前身", e: "The new unit is safer than its <b>predecessor</b>." },
  { w: "preliminary", p: "/prɪˈlɪmɪnəri/", m: "adj. 初步的", e: "<b>Preliminary</b> results support the hypothesis." },
  { w: "premise", p: "/ˈpremɪs/", m: "n. 前提；厂区", e: "The design rests on one key <b>premise</b>." },
  { w: "prescribe", p: "/prɪˈskraɪb/", m: "v. 规定；开处方", e: "The code <b>prescribes</b> a minimum wall thickness." },
  { w: "prestige", p: "/preˈstiːʒ/", m: "n. 声望", e: "The institute enjoys high <b>prestige</b> in catalysis." },
  { w: "prominent", p: "/ˈprɒmɪnənt/", m: "adj. 突出的；著名的", e: "She became a <b>prominent</b> voice in process safety." },
  { w: "prone", p: "/prəʊn/", m: "adj. 易于…的（prone to）", e: "Cast iron is <b>prone to</b> brittle fracture." },
  { w: "propel", p: "/prəˈpel/", m: "v. 推进，驱动", e: "Steam <b>propels</b> the turbine blades." },
  { w: "provoke", p: "/prəˈvəʊk/", m: "v. 激起；挑衅", e: "The closure <b>provoked</b> a heated debate." },
  { w: "proximity", p: "/prɒkˈsɪməti/", m: "n. 邻近，接近", e: "Housing in <b>proximity</b> to the plant was relocated." },
  { w: "quest", p: "/kwest/", m: "n. 追求，探寻", e: "The <b>quest</b> for greener solvents continues." },
  { w: "quotation", p: "/kwəʊˈteɪʃn/", m: "n. 引语；报价", e: "Begin the essay with a famous <b>quotation</b>." },
  { w: "radiant", p: "/ˈreɪdiənt/", m: "adj. 辐射的；容光焕发的", e: "<b>Radiant</b> heat from the furnace warms the coils." },
  { w: "radical", p: "/ˈrædɪkl/", m: "adj. 根本的；激进的 n. 自由基", e: "A <b>radical</b> redesign cut energy use by 40%." },
  { w: "random", p: "/ˈrændəm/", m: "adj. 随机的", e: "The auditor picked a <b>random</b> batch record." },
  { w: "rational", p: "/ˈræʃnəl/", m: "adj. 理性的", e: "Make a <b>rational</b> choice based on the data." },
  { w: "readily", p: "/ˈredɪli/", m: "adv. 容易地；乐意地", e: "The data are <b>readily</b> available in the historian." },
  { w: "reap", p: "/riːp/", m: "v. 收获", e: "Early adopters <b>reaped</b> the largest savings." },
  { w: "reassure", p: "/ˌriːəˈʃʊə/", m: "v. 安慰，使放心", e: "The manager <b>reassured</b> the inspectors." },
  { w: "reckless", p: "/ˈrekləs/", m: "adj. 鲁莽的", e: "Skipping the permit was a <b>reckless</b> act." },
  { w: "reckon", p: "/ˈrekən/", m: "v. 认为；估算", e: "We <b>reckon</b> the payback period at two years." },
  { w: "reclaim", p: "/rɪˈkleɪm/", m: "v. 回收；开垦", e: "The unit <b>reclaims</b> solvent from the waste stream." },
  { w: "reconcile", p: "/ˈrekənsaɪl/", m: "v. 调和；核对", e: "It is hard to <b>reconcile</b> speed with safety." },
  { w: "refine", p: "/rɪˈfaɪn/", m: "v. 精炼；改进", e: "Each revision <b>refined</b> the model further." },
  { w: "refrain", p: "/rɪˈfreɪn/", m: "v. 抑制（refrain from）", e: "Staff must <b>refrain from</b> smoking on site." },
  { w: "relay", p: "/ˈriːleɪ/", m: "n. 继电器 v. 传递", e: "A faulty <b>relay</b> tripped the whole train." },
  { w: "reluctant", p: "/rɪˈlʌktənt/", m: "adj. 不情愿的", e: "Firms were <b>reluctant</b> to invest in new pumps." },
  { w: "render", p: "/ˈrendə/", m: "v. 使成为；给予", e: "The error <b>rendered</b> the batch useless." },
  { w: "repel", p: "/rɪˈpel/", m: "v. 排斥；击退", e: "The coating <b>repels</b> water and oil." },
  { w: "resilient", p: "/rɪˈzɪliənt/", m: "adj. 有韧性的；恢复快的", e: "The supply chain proved <b>resilient</b> to the shock." },
  { w: "restrain", p: "/rɪˈstreɪn/", m: "v. 抑制，限制", e: "Clamps <b>restrain</b> the pipe against vibration." },
  { w: "resume", p: "/rɪˈzjuːm/", m: "v. 恢复 n. 简历", e: "Production <b>resumed</b> after the safety check." },
  { w: "retail", p: "/ˈriːteɪl/", m: "n./adj. 零售（的）", e: "The brand moved into <b>retail</b> packaging." },
  { w: "revenue", p: "/ˈrevənjuː/", m: "n. 收入，营收", e: "Licensing added a new <b>revenue</b> stream." },
  { w: "revive", p: "/rɪˈvaɪv/", m: "v. 复苏，使复兴", e: "New orders <b>revived</b> the idle production line." },
  { w: "rigorous", p: "/ˈrɪɡərəs/", m: "adj. 严格的，缜密的", e: "The method passed <b>rigorous</b> validation." },
  { w: "robust", p: "/rəʊˈbʌst/", m: "adj. 稳健的；坚固的", e: "The control loop stays <b>robust</b> under load changes." },
  { w: "ritual", p: "/ˈrɪtʃuəl/", m: "n. 仪式；惯例", e: "The pre-shift briefing became a daily <b>ritual</b>." },
  { w: "sacred", p: "/ˈseɪkrɪd/", m: "adj. 神圣的", e: "Mount Tai is a <b>sacred</b> site in Chinese culture." },
  { w: "safeguard", p: "/ˈseɪfɡɑːd/", m: "v./n. 保护；保障措施", e: "Interlocks <b>safeguard</b> the reactor against overpressure." },
  { w: "saturate", p: "/ˈsætʃəreɪt/", m: "v. 使饱和", e: "The gas leaving the tower is fully <b>saturated</b>." },
  { w: "scatter", p: "/ˈskætə/", m: "v. 散射；散布", e: "Fine droplets <b>scatter</b> the incoming light." },
  { w: "scenario", p: "/səˈnɑːriəʊ/", m: "n. 情景，方案", e: "We simulated a power-failure <b>scenario</b>." },
  { w: "scrutiny", p: "/ˈskruːtəni/", m: "n. 仔细审查", e: "Emissions data face growing public <b>scrutiny</b>." },
  { w: "segment", p: "/ˈseɡmənt/", m: "n. 段；部分 v. 分割", e: "Each pipe <b>segment</b> has its own rating." },
  { w: "sentiment", p: "/ˈsentɪmənt/", m: "n. 情绪，观点", e: "Market <b>sentiment</b> turned against coal projects." },
  { w: "sequence", p: "/ˈsiːkwəns/", m: "n. 顺序；序列", e: "Follow the start-up <b>sequence</b> exactly." },
  { w: "severe", p: "/sɪˈvɪə/", m: "adj. 严重的；剧烈的", e: "The storm caused <b>severe</b> damage to the tank farm." },
  { w: "shrink", p: "/ʃrɪŋk/", m: "v. 收缩，缩小", e: "The resin beads <b>shrink</b> when dried." },
  { w: "simulate", p: "/ˈsɪmjuleɪt/", m: "v. 模拟", e: "Aspen can <b>simulate</b> the whole flowsheet." },
  { w: "skeptical", p: "/ˈskeptɪkl/", m: "adj. 怀疑的", e: "Reviewers were <b>skeptical</b> about the claims." },
  { w: "solemn", p: "/ˈsɒləm/", m: "adj. 庄严的；严肃的", e: "The signing ceremony was brief but <b>solemn</b>." },
  { w: "sophisticated", p: "/səˈfɪstɪkeɪtɪd/", m: "adj. 精密的；复杂的", e: "A <b>sophisticated</b> controller trims the feed rate." },
  { w: "spacious", p: "/ˈspeɪʃəs/", m: "adj. 宽敞的", e: "The new control room is bright and <b>spacious</b>." },
  { w: "span", p: "/spæn/", m: "n. 跨度 v. 横跨", e: "The bridge has a main <b>span</b> of 200 meters." },
  { w: "spark", p: "/spɑːk/", m: "n. 火花 v. 引发", e: "A static <b>spark</b> can ignite the vapor." },
  { w: "specify", p: "/ˈspesɪfaɪ/", m: "v. 明确规定", e: "The client <b>specified</b> 316L stainless steel." },
  { w: "spectrum", p: "/ˈspektrəm/", m: "n. 光谱；范围", e: "The analyzer scans the full UV <b>spectrum</b>." },
  { w: "spontaneous", p: "/spɒnˈteɪniəs/", m: "adj. 自发的", e: "The polymerization proved <b>spontaneous</b> at high temperature." },
  { w: "stationary", p: "/ˈsteɪʃənri/", m: "adj. 静止的；固定的", e: "Use a <b>stationary</b> phase of silica gel." },
  { w: "stimulate", p: "/ˈstɪmjuleɪt/", m: "v. 刺激，激励", e: "Tax breaks <b>stimulate</b> investment in recycling." },
  { w: "straightforward", p: "/ˌstreɪtˈfɔːwəd/", m: "adj. 简单直接的", e: "The fix is <b>straightforward</b>: replace the gasket." },
  { w: "strive", p: "/straɪv/", m: "v. 努力，力求", e: "We <b>strive</b> for zero discharge." },
  { w: "stubborn", p: "/ˈstʌbən/", m: "adj. 顽固的；难对付的", e: "The <b>stubborn</b> leak resisted three repairs." },
  { w: "stumble", p: "/ˈstʌmbl/", m: "v. 绊倒；偶然发现", e: "They <b>stumbled upon</b> a better catalyst by accident." },
  { w: "subordinate", p: "/səˈbɔːdɪnət/", m: "adj. 从属的 n. 下属", e: "Cost goals are <b>subordinate</b> to safety." },
  { w: "subtle", p: "/ˈsʌtl/", m: "adj. 微妙的，细微的", e: "A <b>subtle</b> shift in pH changed the color." },
  { w: "surpass", p: "/səˈpɑːs/", m: "v. 超过，胜过", e: "Sales <b>surpassed</b> all forecasts this quarter." },
  { w: "tackle", p: "/ˈtækl/", m: "v. 处理，解决", e: "A task force was set up to <b>tackle</b> the fouling." },
  { w: "tangible", p: "/ˈtændʒəbl/", m: "adj. 有形的；实实在在的", e: "The upgrade brought <b>tangible</b> savings." },
  { w: "tedious", p: "/ˈtiːdiəs/", m: "adj. 单调乏味的", e: "Manual data entry is slow and <b>tedious</b>." },
  { w: "tentative", p: "/ˈtentətɪv/", m: "adj. 暂定的；试探性的", e: "We drew up a <b>tentative</b> schedule for the shutdown." },
  { w: "terrain", p: "/təˈreɪn/", m: "n. 地形", e: "The pipeline crosses rough <b>terrain</b> for 40 km." },
  { w: "testify", p: "/ˈtestɪfaɪ/", m: "v. 作证；证明", e: "The logs <b>testify</b> that the alarm rang twice." },
  { w: "thrive", p: "/θraɪv/", m: "v. 茁壮成长；兴旺", e: "The startup <b>thrived</b> on battery materials." },
  { w: "tilt", p: "/tɪlt/", m: "v./n. 倾斜", e: "The column was given a slight <b>tilt</b> to aid drainage." },
  { w: "timid", p: "/ˈtɪmɪd/", m: "adj. 胆怯的", e: "Do not be <b>timid</b> in the interview." },
  { w: "tolerate", p: "/ˈtɒləreɪt/", m: "v. 容忍；耐受", e: "The seal material <b>tolerates</b> strong acids." },
  { w: "torrent", p: "/ˈtɒrənt/", m: "n. 洪流", e: "A <b>torrent</b> of water burst from the joint." },
  { w: "trait", p: "/treɪt/", m: "n. 特征，特质", e: "Curiosity is the key <b>trait</b> of a good engineer." },
  { w: "tranquil", p: "/ˈtræŋkwɪl/", m: "adj. 宁静的", e: "The campus lake is calm and <b>tranquil</b>." },
  { w: "transcend", p: "/trænˈsend/", m: "v. 超越", e: "Good design <b>transcends</b> national standards." },
  { w: "transit", p: "/ˈtrænzɪt/", m: "n. 运输；中转", e: "The cargo was damaged in <b>transit</b>." },
  { w: "transparent", p: "/trænsˈpærənt/", m: "adj. 透明的；公开的", e: "Keep the reporting process <b>transparent</b>." },
  { w: "tremendous", p: "/trəˈmendəs/", m: "adj. 巨大的", e: "The retrofit brought <b>tremendous</b> gains." },
  { w: "trivial", p: "/ˈtrɪviəl/", m: "adj. 琐碎的，不重要的", e: "Do not skip a <b>trivial</b> deviation in the record." },
  { w: "tumble", p: "/ˈtʌmbl/", m: "v. 跌落；暴跌", e: "Prices <b>tumbled</b> after the new supply came online." },
  { w: "ultimate", p: "/ˈʌltɪmət/", m: "adj. 最终的；根本的", e: "Safety is the <b>ultimate</b> criterion of the design." },
  { w: "unanimous", p: "/juˈnænɪməs/", m: "adj. 一致同意的", e: "The review board was <b>unanimous</b> in approving the change." },
  { w: "undergo", p: "/ˌʌndəˈɡəʊ/", m: "v. 经历，承受", e: "The vessel will <b>undergo</b> inspection next week." },
  { w: "underlie", p: "/ˌʌndəˈlaɪ/", m: "v. 构成…的基础", e: "Mass transfer <b>underlies</b> all separation processes." },
  { w: "undertake", p: "/ˌʌndəˈteɪk/", m: "v. 承担，从事", e: "The lab will <b>undertake</b> the stability study." },
  { w: "unify", p: "/ˈjuːnɪfaɪ/", m: "v. 统一", e: "The merger will <b>unify</b> the two quality systems." },
  { w: "unprecedented", p: "/ʌnˈpresɪdentɪd/", m: "adj. 前所未有的", e: "The heat wave set an <b>unprecedented</b> record." },
  { w: "upgrade", p: "/ˈʌpɡreɪd/", m: "v./n. 升级", e: "The plant will <b>upgrade</b> its DCS next year." },
  { w: "urgency", p: "/ˈɜːdʒənsi/", m: "n. 紧迫性", e: "There is no <b>urgency</b> — plan the shutdown calmly." },
  { w: "utilize", p: "/ˈjuːtəlaɪz/", m: "v. 利用", e: "The plant <b>utilizes</b> waste heat for district heating." },
  { w: "vague", p: "/veɪɡ/", m: "adj. 模糊的", e: "The instructions were too <b>vague</b> to follow." },
  { w: "valid", p: "/ˈvælɪd/", m: "adj. 有效的；有根据的", e: "The permit is <b>valid</b> for one shift only." },
  { w: "vanish", p: "/ˈvænɪʃ/", m: "v. 消失", e: "The foam <b>vanished</b> after the antifoam dose." },
  { w: "variable", p: "/ˈveəriəbl/", m: "n. 变量 adj. 可变的", e: "Temperature is the key <b>variable</b> in the model." },
  { w: "venture", p: "/ˈventʃə/", m: "n. 风险企业 v. 冒险", e: "The joint <b>venture</b> builds electrolyzer stacks." },
  { w: "verify", p: "/ˈverɪfaɪ/", m: "v. 核实，验证", e: "QC must <b>verify</b> every batch before release." },
  { w: "versatile", p: "/ˈvɜːsətaɪl/", m: "adj. 多用途的；多才多艺的", e: "A <b>versatile</b> pilot plant handles many recipes." },
  { w: "vicinity", p: "/vəˈsɪnəti/", m: "n. 附近，邻近", e: "No ignition sources are allowed in the <b>vicinity</b>." },
  { w: "vigor", p: "/ˈvɪɡə/", m: "n. 活力，精力", e: "She defended the design with great <b>vigor</b>." },
  { w: "violate", p: "/ˈvaɪəleɪt/", m: "v. 违反；侵犯", e: "The plant <b>violated</b> the discharge limit twice." },
  { w: "virtual", p: "/ˈvɜːtʃuəl/", m: "adj. 虚拟的；事实上的", e: "New hires train on a <b>virtual</b> plant first." },
  { w: "visualize", p: "/ˈvɪʒuəlaɪz/", m: "v. 可视化；想象", e: "Charts help <b>visualize</b> the trend in yield." },
  { w: "vital", p: "/ˈvaɪtl/", m: "adj. 至关重要的", e: "Cooling water is <b>vital</b> to safe operation." },
  { w: "vivid", p: "/ˈvɪvɪd/", m: "adj. 生动的；鲜艳的", e: "The lecture left a <b>vivid</b> impression on me." },
  { w: "wary", p: "/ˈweəri/", m: "adj. 警惕的（wary of）", e: "Be <b>wary of</b> unsourced online data." },
  { w: "weave", p: "/wiːv/", m: "v. 编织；编排", e: "The speaker <b>wove</b> three case studies together." },
  { w: "whereby", p: "/weəˈbaɪ/", m: "adv. 借以，由此", e: "A system <b>whereby</b> alarms auto-escalate was adopted." },
  { w: "wholesome", p: "/ˈhəʊlsəm/", m: "adj. 有益健康的", e: "The canteen serves simple, <b>wholesome</b> meals." },
  { w: "widespread", p: "/ˈwaɪdspred/", m: "adj. 广泛的，普遍的", e: "The practice is <b>widespread</b> across the industry." },
  { w: "withdraw", p: "/wɪðˈdrɔː/", m: "v. 撤回；取款", e: "The company <b>withdrew</b> the risky product." },
  { w: "withstand", p: "/wɪðˈstænd/", m: "v. 承受，经受", e: "The vessel must <b>withstand</b> 2 MPa." },
  { w: "witness", p: "/ˈwɪtnəs/", m: "n. 目击者 v. 见证", e: "The industry <b>witnessed</b> rapid change last decade." },
  { w: "yield", p: "/jiːld/", m: "n. 产量 v. 屈服；产出", e: "The reactor gives a <b>yield</b> of 92 percent." },
  { w: "zeal", p: "/ziːl/", m: "n. 热情，热忱", e: "She pursued research with great <b>zeal</b>." },
  { w: "zone", p: "/zəʊn/", m: "n. 区域", e: "The site has a marked hazardous <b>zone</b> classification." }
];

/* ---------- 六级翻译 · 中国文化高频表达 ---------- */
window.MST_CN_EXPR = [
  ["历史文物", "historical relics"], ["朝代", "dynasty"], ["皇帝", "emperor"],
  ["丝绸之路", "the Silk Road"], ["四大发明", "the Four Great Inventions"],
  ["造纸术", "papermaking"], ["印刷术", "printing"], ["火药", "gunpowder"], ["指南针", "the compass"],
  ["儒家思想", "Confucianism"], ["孔子", "Confucius"], ["道教", "Taoism"], ["佛教", "Buddhism"],
  ["寺庙", "temple"], ["兵马俑", "the Terracotta Warriors"], ["长城", "the Great Wall"],
  ["故宫", "the Forbidden City / the Palace Museum"], ["书法", "calligraphy"],
  ["京剧", "Peking Opera"], ["武术", "martial arts"], ["剪纸", "paper cutting"],
  ["刺绣", "embroidery"], ["瓷器", "porcelain"], ["丝绸之路经济带", "the Silk Road Economic Belt"],
  ["茶文化", "tea culture"], ["中医药", "traditional Chinese medicine"], ["针灸", "acupuncture"],
  ["春节", "the Spring Festival"], ["中秋节", "the Mid-Autumn Festival"],
  ["端午节", "the Dragon Boat Festival"], ["元宵节", "the Lantern Festival"],
  ["团圆", "family reunion"], ["灯笼", "lantern"], ["舞龙舞狮", "dragon and lion dances"],
  ["饺子", "dumplings"], ["月饼", "mooncakes"], ["粽子", "zongzi (sticky rice dumplings)"],
  ["改革开放", "reform and opening-up"], ["一带一路", "the Belt and Road Initiative"],
  ["可持续发展", "sustainable development"], ["城市化", "urbanization"],
  ["基础设施", "infrastructure"], ["高铁", "high-speed rail"],
  ["电子商务", "e-commerce"], ["移动支付", "mobile payment"],
  ["脱贫攻坚", "poverty alleviation"], ["全面小康", "a moderately prosperous society"],
  ["碳中和", "carbon neutrality"], ["新能源", "new/renewable energy"],
  ["人工智能", "artificial intelligence"], ["科技创新", "technological innovation"],
  ["经济繁荣", "economic prosperity"], ["文化遗产", "cultural heritage"],
  ["名扬中外", "enjoy a great reputation at home and abroad"],
  ["源远流长", "have a long history"], ["博大精深", "broad and profound"],
  ["随着…的发展", "with the development of…"],
  ["越来越多的人", "an increasing number of people"],
  ["在…中扮演重要角色", "play an important role in…"],
  ["被视为", "be regarded/viewed as"], ["起源于", "originate from / date back to"],
  ["中国传统节日", "traditional Chinese festivals"], ["清明节", "the Tomb-Sweeping Day"],
  ["重阳节", "the Double Ninth Festival"], ["七夕节", "the Double Seventh Festival"],
  ["腊八节", "the Laba Festival"], ["二十四节气", "the 24 solar terms"],
  ["生肖", "Chinese zodiac"], ["属相", "zodiac animal signs"], ["风水", "feng shui"],
  ["汉字", "Chinese characters"], ["普通话", "Mandarin"], ["成语", "Chinese idioms"],
  ["唐诗宋词", "poems of the Tang and Song dynasties"], ["四大名著", "the Four Great Classical Novels"],
  ["文房四宝", "the four treasures of the study"], ["国画", "traditional Chinese painting"],
  ["围棋", "Go (the board game)"], ["象棋", "Chinese chess"], ["太极拳", "Tai Chi"],
  ["中医", "traditional Chinese medicine"], ["草药", "herbal medicine"], ["按摩", "massage"],
  ["药膳", "medicated diet"], ["茶道", "tea ceremony"], ["茅台", "Moutai"],
  ["景德镇", "Jingdezhen (the porcelain capital)"], ["苏绣", "Su embroidery"],
  ["皮影戏", "shadow puppetry"], ["相声", "crosstalk"], ["杂技", "acrobatics"],
  ["庙会", "temple fair"], ["祭祀", "sacrificial ceremony"], ["祭祖", "ancestor worship"],
  ["年夜饭", "the family reunion dinner on New Year's Eve"], ["压岁钱", "lucky money"],
  ["春联", "Spring Festival couplets"], ["放鞭炮", "set off firecrackers"],
  ["赏月", "admire the full moon"], ["赛龙舟", "dragon boat racing"],
  ["登高", "climb mountains"], ["赏菊", "admire chrysanthemums"],
  ["黄山", "Mount Huangshan"], ["泰山", "Mount Tai"], ["长江", "the Yangtze River"],
  ["黄河", "the Yellow River"], ["珠江", "the Pearl River"], ["太湖", "Taihu Lake"],
  ["西湖", "the West Lake"], ["桂林山水", "the landscape of Guilin"],
  ["九寨沟", "Jiuzhaigou Valley"], ["布达拉宫", "the Potala Palace"],
  ["莫高窟", "the Mogao Grottoes"], ["苏州园林", "the classical gardens of Suzhou"],
  ["大运河", "the Grand Canal"], ["都江堰", "the Dujiangyan irrigation system"],
  ["秦始皇", "Emperor Qin Shi Huang"], ["唐太宗", "Emperor Taizong of the Tang Dynasty"],
  ["丝绸之路上的商队", "caravans on the Silk Road"], ["古都", "ancient capital"],
  ["文明古国", "a country with an ancient civilization"],
  ["社会主义现代化强国", "a great modern socialist country"],
  ["创新型国家", "an innovative country"], ["科教兴国", "rejuvenating the country through science and education"],
  ["人才强国", "strengthening the country through talent"], ["绿色发展", "green development"],
  ["生态文明", "ecological civilization"], ["节能减排", "energy conservation and emission reduction"],
  ["循环经济", "circular economy"], ["可再生能源", "renewable energy"],
  ["绿色发展理念", "the concept of green development"], ["环境保护", "environmental protection"],
  ["污染治理", "pollution control"], ["生态平衡", "ecological balance"],
  ["快递业", "the express delivery industry"], ["共享经济", "the sharing economy"],
  ["数字经济", "the digital economy"], ["直播带货", "livestream e-commerce"],
  ["网购", "online shopping"], ["智能手机", "smartphones"],
  ["5G 网络", "5G networks"], ["大数据", "big data"], ["云计算", "cloud computing"],
  ["机器人", "robots"], ["自动化", "automation"], ["载人航天", "manned spaceflight"],
  ["探月工程", "the lunar exploration program"], ["空间站", "space station"],
  ["高速铁路网", "high-speed railway network"], ["桥梁工程", "bridge engineering"],
  ["港口", "ports"], ["对外贸易", "foreign trade"], ["国内生产总值", "GDP"],
  ["人均收入", "per capita income"], ["人民生活水平", "people's living standards"],
  ["教育公平", "equal access to education"], ["义务教育", "compulsory education"],
  ["高等教育", "higher education"], ["终身学习", "lifelong learning"],
  ["社会保障体系", "the social security system"], ["医疗卫生", "health care"],
  ["乡村振兴", "rural revitalization"], ["城镇化进程", "the process of urbanization"],
  ["历史悠久", "have a time-honored history"], ["闻名遐迩", "be well-known far and near"],
  ["独具特色", "be distinctive / unique"], ["丰富多彩", "rich and colorful"],
  ["蓬勃发展", "flourish / boom"], ["日新月异", "change with each passing day"],
  ["举世瞩目", "attract worldwide attention"], ["繁荣昌盛", "prosperous and thriving"],
  ["深入人心", "take root in people's hearts"], ["方兴未艾", "be in the ascendant"],
  ["面临挑战", "be confronted with challenges"], ["采取措施", "take measures"],
  ["发挥优势", "give play to one's advantages"], ["取得显著成就", "achieve remarkable success"],
  ["促进交流", "promote exchanges"], ["增进了解", "enhance mutual understanding"],
  ["保护环境", "protect the environment"], ["归根结底", "in the final analysis"],
  ["不可否认", "it is undeniable that…"], ["值得一提的是", "it is worth mentioning that…"],
  ["正因如此", "it is for this reason that…"], ["综上所述", "in conclusion / to sum up"]
];
